import type { DemoDish, DemoYieldTest } from './spec';

/**
 * Pruebas de rendimiento, elaboraciones (sub-recetas) y platos de carta de la taberna de demostración.
 * Gramajes de cocina profesional; cantidades de fritura = aceite absorbido + reposición proporcional.
 * Los números están pensados para que el semáforo de food cost muestre verdes, ámbar y rojos, y la
 * matriz de ingeniería de menú tenga estrellas, caballos de batalla, enigmas y perros.
 */

export const DEMO_YIELD_TESTS: DemoYieldTest[] = [
  {
    key: 'yt_pulpo',
    name: 'Pulpo crudo congelado T3 · cocción',
    product: 'pulpo',
    daysAgo: 38,
    grossWeightKg: 2.5,
    thawLossPct: 8,
    cookingLossPct: 45,
    portionKg: 0.15,
    outputs: [
      { name: 'Pulpo limpio (patas y cuerpo)', weightKg: 2.2, kind: 'principal' },
      { name: 'Cabeza interior, ojos y pico', weightKg: 0.1, kind: 'desperdicio' },
    ],
    notes: 'Descongelado 48 h en cámara. Cocción: asustar tres veces y 40 min a fuego suave; reposo 10 min en el agua.',
  },
  {
    key: 'yt_salmon',
    name: 'Salmón noruego entero · fileteado',
    product: 'salmon',
    daysAgo: 80,
    grossWeightKg: 5.2,
    cookingLossPct: 18,
    portionKg: 0.18,
    outputs: [
      { name: 'Lomos limpios sin piel', weightKg: 3.2, kind: 'principal' },
      { name: 'Ventresca y recortes (tartar, rillettes)', weightKg: 0.45, kind: 'subproducto', valuePerKg: 6 },
      { name: 'Cabeza, espinas y piel', weightKg: 1.4, kind: 'desperdicio' },
    ],
    notes: 'Diferencia sin registrar = goteo y sangrado durante el fileteado.',
  },
  {
    key: 'yt_solomillo',
    name: 'Solomillo de ternera entero · limpieza',
    product: 'solomillo',
    daysAgo: 20,
    grossWeightKg: 2.3,
    cookingLossPct: 22,
    portionKg: 0.2,
    outputs: [
      { name: 'Solomillo limpio (cabeza, centro y punta)', weightKg: 1.85, kind: 'principal' },
      { name: 'Cordón (para guisos)', weightKg: 0.25, kind: 'subproducto', valuePerKg: 9 },
      { name: 'Grasa y nervios', weightKg: 0.18, kind: 'desperdicio' },
    ],
    notes: 'Cordón aprovechado en las carrilleras y en el fondo oscuro. Punto de servicio: al punto (22 % de merma a la brasa).',
  },
];

export const DEMO_ELABORATIONS: DemoDish[] = [
  {
    key: 'fondo',
    name: 'Fondo oscuro de ternera',
    kind: 'elaboracion',
    section: 'Fondos',
    portions: 1,
    yieldQty: 3,
    yieldUnit: 'l',
    status: 'revisado',
    createdDaysAgo: 90,
    tags: ['base'],
    procedure:
      'Tostar los huesos en horno a 220 °C durante 45 min. Rehogar la verdura en el aceite hasta caramelizar, añadir el tomate y reducir. ' +
      'Desglasar la bandeja con el vino, juntar todo con 6 l de agua fría y las hierbas, y cocer 6 h a fuego mínimo desespumando. ' +
      'Colar, desgrasar en frío y reducir hasta 3 l. Abatir y conservar a 4 °C (5 días) o congelar en bolsas de 1 l.',
    items: [
      { name: 'Huesos de ternera', ref: 'p:huesos', quantity: 3, unit: 'kg', basis: 'bruta' },
      { name: 'Zanahoria', ref: 'p:zanahoria', quantity: 300, unit: 'g', basis: 'bruta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 300, unit: 'g', basis: 'bruta' },
      { name: 'Puerro', ref: 'p:puerro', quantity: 250, unit: 'g', basis: 'bruta' },
      { name: 'Apio', ref: 'p:apio', quantity: 150, unit: 'g', basis: 'bruta' },
      { name: 'Tomate triturado', ref: 'p:tomate_triturado', quantity: 200, unit: 'g', basis: 'neta' },
      { name: 'Vino tinto', ref: 'p:vino_tinto', quantity: 500, unit: 'ml', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 50, unit: 'ml', basis: 'neta' },
      { name: 'Laurel', ref: 'p:laurel', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Pimienta negra', ref: 'p:pimienta', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'brava',
    name: 'Salsa brava',
    kind: 'elaboracion',
    section: 'Salsas',
    portions: 1,
    yieldQty: 1,
    yieldUnit: 'l',
    status: 'revisado',
    createdDaysAgo: 90,
    tags: ['receta de la casa'],
    procedure:
      'Pochar la cebolla y el ajo picados en el aceite a fuego suave 15 min. Añadir la harina y tostar 2 min; fuera del fuego, ' +
      'incorporar los pimentones y la cayena. Mojar con el fondo caliente y el tomate, cocer 20 min, añadir el vinagre y la sal, ' +
      'triturar fino y colar. Rinde 1 l. Conservar a 4 °C un máximo de 5 días.',
    items: [
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 120, unit: 'ml', basis: 'neta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 200, unit: 'g', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 50, unit: 'g', basis: 'neta' },
      { name: 'Pimentón de la Vera dulce', ref: 'p:pimenton_dulce', quantity: 25, unit: 'g', basis: 'neta' },
      { name: 'Pimentón de la Vera picante', ref: 'p:pimenton_picante', quantity: 8, unit: 'g', basis: 'neta' },
      { name: 'Guindilla cayena', ref: 'p:cayena', quantity: 2, unit: 'g', basis: 'neta' },
      { name: 'Tomate triturado', ref: 'p:tomate_triturado', quantity: 250, unit: 'g', basis: 'neta' },
      { name: 'Fondo oscuro de ternera', ref: 'd:fondo', quantity: 500, unit: 'ml', basis: 'neta' },
      { name: 'Vinagre de Jerez', ref: 'p:vinagre_jerez', quantity: 20, unit: 'ml', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 8, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'alioli',
    name: 'Alioli',
    kind: 'elaboracion',
    section: 'Salsas',
    portions: 1,
    yieldQty: 0.5,
    yieldUnit: 'kg',
    status: 'revisado',
    createdDaysAgo: 90,
    tags: ['receta de la casa'],
    procedure:
      'Emulsionar con túrmix el huevo, el ajo, el zumo de limón y la sal, añadiendo los aceites en hilo fino hasta obtener una textura firme. ' +
      'Rinde 0,5 kg. Conservar por debajo de 4 °C y consumir en 24 h.',
    items: [
      { name: 'Aceite de girasol alto oleico', ref: 'p:girasol', quantity: 300, unit: 'ml', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 100, unit: 'ml', basis: 'neta' },
      { name: 'Huevo', ref: 'p:huevos', quantity: 2, unit: 'ud', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 30, unit: 'g', basis: 'neta' },
      { name: 'Zumo de limón', ref: 'p:limon', quantity: 30, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 4, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'masa_croquetas',
    name: 'Masa de croquetas de jamón',
    kind: 'elaboracion',
    section: 'Bases',
    portions: 1,
    yieldQty: 2.4,
    yieldUnit: 'kg',
    status: 'revisado',
    createdDaysAgo: 90,
    tags: ['receta de la casa'],
    procedure:
      'Sudar la cebolla muy picada en la mantequilla y el aceite, añadir los taquitos de jamón y rehogar 2 min. Incorporar la harina y cocinar ' +
      '5 min sin que tome color. Añadir la leche caliente poco a poco sin dejar de remover y cocer 25 min a fuego suave hasta que se despegue ' +
      'de las paredes. Sazonar con nuez moscada y sal, extender en bandeja, filmar a piel y enfriar 12 h. Rinde 2,4 kg (60 croquetas de 40 g).',
    items: [
      { name: 'Mantequilla', ref: 'p:mantequilla', quantity: 180, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 60, unit: 'ml', basis: 'neta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 150, unit: 'g', basis: 'bruta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 200, unit: 'g', basis: 'neta' },
      { name: 'Leche entera', ref: 'p:leche', quantity: 1.8, unit: 'l', basis: 'neta' },
      { name: 'Taquitos de jamón ibérico', ref: 'p:taquitos', quantity: 350, unit: 'g', basis: 'neta' },
      { name: 'Nuez moscada', ref: 'p:nuez_moscada', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 5, unit: 'g', basis: 'neta' },
    ],
  },
];

export const DEMO_DISHES: DemoDish[] = [
  // ───────────── Para picar ─────────────
  {
    key: 'bravas',
    name: 'Patatas bravas',
    kind: 'plato',
    section: 'Para picar',
    description: 'Patata agria frita en dos tiempos, salsa brava de la casa y alioli.',
    menuPrice: 6.0,
    portions: 1,
    unitsSold: 305,
    status: 'revisado',
    tags: ['receta de la casa', 'para compartir'],
    createdDaysAgo: 88,
    procedure: 'Cortar en gajos irregulares, confitar a 140 °C 8 min y freír a 185 °C hasta dorar. Salsear con la brava templada y puntos de alioli.',
    items: [
      { name: 'Patata agria', ref: 'p:patata', quantity: 450, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de girasol (fritura)', ref: 'p:girasol', quantity: 100, unit: 'ml', basis: 'neta', note: 'Absorción + reposición de la freidora' },
      { name: 'Salsa brava', ref: 'd:brava', quantity: 80, unit: 'ml', basis: 'neta' },
      { name: 'Alioli', ref: 'd:alioli', quantity: 35, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'croquetas',
    name: 'Croquetas de jamón ibérico',
    kind: 'plato',
    section: 'Para picar',
    description: 'Ocho croquetas cremosas de jamón ibérico, rebozado crujiente.',
    menuPrice: 9.5,
    portions: 1,
    unitsSold: 240,
    status: 'revisado',
    tags: ['receta de la casa'],
    createdDaysAgo: 88,
    procedure: 'Bolear 8 piezas de 40 g de masa, pasar por harina, huevo y pan rallado. Freír a 180 °C 2–3 min. Servir recién hechas.',
    items: [
      { name: 'Masa de croquetas de jamón', ref: 'd:masa_croquetas', quantity: 320, unit: 'g', basis: 'neta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Huevo', ref: 'p:huevos', quantity: 1, unit: 'ud', basis: 'bruta' },
      { name: 'Pan rallado', ref: 'p:pan_rallado', quantity: 50, unit: 'g', basis: 'neta' },
      { name: 'Aceite de girasol (fritura)', ref: 'p:girasol', quantity: 60, unit: 'ml', basis: 'neta' },
    ],
  },
  {
    key: 'tortilla',
    name: 'Tortilla de patatas',
    kind: 'plato',
    section: 'Para picar',
    description: 'Jugosa, con cebolla pochada. Precio por ración (1/6 de tortilla).',
    menuPrice: 3.8,
    portions: 6,
    unitsSold: 270,
    status: 'revisado',
    tags: ['sin gluten'],
    createdDaysAgo: 88,
    procedure:
      'Confitar la patata en láminas y la cebolla en el aceite a 120 °C hasta que estén tiernas. Escurrir, mezclar con los huevos batidos y ' +
      'la sal, reposar 10 min y cuajar en sartén de 26 cm dejando el centro jugoso. Salen 6 raciones.',
    items: [
      { name: 'Patata agria', ref: 'p:patata', quantity: 1.2, unit: 'kg', basis: 'bruta' },
      { name: 'Huevos camperos', ref: 'p:huevos', quantity: 8, unit: 'ud', basis: 'bruta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 300, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 200, unit: 'ml', basis: 'neta', note: 'Aceite consumido en el confitado' },
      { name: 'Sal', ref: 'p:sal', quantity: 10, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'jamon',
    name: 'Jamón ibérico de bellota',
    kind: 'plato',
    section: 'Para picar',
    description: 'Cortado a cuchillo (90 g), con picos artesanos.',
    menuPrice: 23.5,
    portions: 1,
    unitsSold: 85,
    status: 'revisado',
    tags: ['sin lactosa'],
    createdDaysAgo: 88,
    procedure: 'Cortar al momento lonchas finas de 4–5 cm, emplatar en abanico a temperatura ambiente (22–24 °C) y acompañar con picos.',
    items: [
      { name: 'Jamón ibérico de bellota', ref: 'p:jamon', quantity: 90, unit: 'g', basis: 'neta' },
      { name: 'Picos de pan', ref: 'p:picos', quantity: 40, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'gambas',
    name: 'Gambas al ajillo',
    kind: 'plato',
    section: 'Para picar',
    description: 'En cazuela de barro con ajo laminado, guindilla y perejil.',
    menuPrice: 14.5,
    portions: 1,
    unitsSold: 88,
    status: 'revisado',
    createdDaysAgo: 88,
    items: [
      { name: 'Gamba blanca pelada', ref: 'p:gamba_pelada', quantity: 180, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 70, unit: 'ml', basis: 'neta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Guindilla cayena', ref: 'p:cayena', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Perejil', ref: 'p:perejil', quantity: 5, unit: 'g', basis: 'neta' },
      { name: 'Picos de pan', ref: 'p:picos', quantity: 30, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'pulpo',
    name: 'Pulpo a la gallega',
    kind: 'plato',
    section: 'Para picar',
    description: 'Sobre cachelos, con pimentón de la Vera, aceite de oliva virgen extra y sal en escamas.',
    menuPrice: 18.5,
    portions: 1,
    unitsSold: 130,
    status: 'revisado',
    tags: ['sin gluten', 'sin lactosa'],
    createdDaysAgo: 88,
    procedure: 'Cortar 150 g de pulpo cocido en rodajas con tijera, templar en el agua de cocción y servir sobre los cachelos. Aliñar al momento.',
    items: [
      { name: 'Pulpo', ref: 'p:pulpo', quantity: 150, unit: 'g', basis: 'cocinada', note: 'Coste según la prueba de rendimiento del pulpo' },
      { name: 'Patata (cachelos)', ref: 'p:patata', quantity: 200, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 25, unit: 'ml', basis: 'neta' },
      { name: 'Pimentón de la Vera dulce', ref: 'p:pimenton_dulce', quantity: 2, unit: 'g', basis: 'neta' },
      { name: 'Pimentón de la Vera picante', ref: 'p:pimenton_picante', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 3, unit: 'g', basis: 'neta' },
      { name: 'Laurel', ref: 'p:laurel', quantity: 0.5, unit: 'g', basis: 'neta' },
    ],
  },

  // ───────────── Entrantes ─────────────
  {
    key: 'ensaladilla',
    name: 'Ensaladilla rusa',
    kind: 'plato',
    section: 'Entrantes',
    description: 'Con ventresca de bonito del norte y picos.',
    menuPrice: 8.5,
    portions: 1,
    unitsSold: 165,
    status: 'revisado',
    createdDaysAgo: 88,
    procedure: 'Cocer patata y zanahoria con piel, pelar y cortar en dados. Mezclar en frío con el huevo, el atún y la mayonesa. Coronar con la ventresca y las aceitunas.',
    items: [
      { name: 'Patata', ref: 'p:patata', quantity: 200, unit: 'g', basis: 'bruta' },
      { name: 'Zanahoria', ref: 'p:zanahoria', quantity: 30, unit: 'g', basis: 'bruta' },
      { name: 'Guisantes', ref: 'p:guisantes', quantity: 25, unit: 'g', basis: 'neta' },
      { name: 'Huevo cocido', ref: 'p:huevos', quantity: 1, unit: 'ud', basis: 'bruta' },
      { name: 'Atún claro en aceite', ref: 'p:atun_lata', quantity: 50, unit: 'g', basis: 'neta' },
      { name: 'Mayonesa', ref: 'p:mayonesa', quantity: 80, unit: 'g', basis: 'neta' },
      { name: 'Ventresca de bonito', ref: 'p:ventresca', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Aceitunas manzanilla', ref: 'p:aceitunas', quantity: 15, unit: 'g', basis: 'neta' },
      { name: 'Picos de pan', ref: 'p:picos', quantity: 20, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'burrata',
    name: 'Burrata con tomate rosa y albahaca',
    kind: 'plato',
    section: 'Entrantes',
    description: 'Burrata cremosa, tomate rosa de temporada, rúcula y aceite de oliva virgen extra.',
    menuPrice: 12.5,
    portions: 1,
    unitsSold: 48,
    status: 'borrador',
    createdDaysAgo: 3,
    notes: 'Plato nuevo leído de la carta. Receta propuesta por la base de recetas local: revisa los gramajes antes de confirmar.',
    items: [
      { name: 'Burrata', ref: 'p:burrata', quantity: 1, unit: 'ud', basis: 'bruta', matchScore: 0.97 },
      { name: 'Tomate rosa', ref: 'p:tomate_rosa', quantity: 220, unit: 'g', basis: 'bruta', matchScore: 0.93 },
      { name: 'Rúcula', ref: 'p:rucula', quantity: 20, unit: 'g', basis: 'neta', matchScore: 1 },
      { name: 'Albahaca fresca', ref: 'p:albahaca', quantity: 5, unit: 'g', basis: 'neta', matchScore: 0.95 },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 25, unit: 'ml', basis: 'neta', matchScore: 0.98 },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 2, unit: 'g', basis: 'neta', matchScore: 0.91 },
      { name: 'Pimienta negra', ref: 'p:pimienta', quantity: 0.5, unit: 'g', basis: 'neta', matchScore: 0.88 },
    ],
  },
  {
    key: 'tataki',
    name: 'Tataki de atún rojo',
    kind: 'plato',
    section: 'Entrantes',
    description: 'Lomo de atún rojo marcado, sésamo tostado, soja, aguacate y cebolleta.',
    menuPrice: 17.0,
    portions: 1,
    unitsSold: 35,
    status: 'borrador',
    createdDaysAgo: 3,
    notes: 'Plato nuevo leído de la carta. Receta propuesta por la base de recetas local: revisa los gramajes antes de confirmar.',
    items: [
      { name: 'Atún rojo', ref: 'p:atun_rojo', quantity: 150, unit: 'g', basis: 'neta', matchScore: 0.94 },
      { name: 'Salsa de soja', ref: 'p:soja', quantity: 20, unit: 'ml', basis: 'neta', matchScore: 1 },
      { name: 'Sésamo tostado', ref: 'p:sesamo', quantity: 5, unit: 'g', basis: 'neta', matchScore: 0.96 },
      { name: 'Aguacate', ref: 'p:aguacate', quantity: 60, unit: 'g', basis: 'neta', matchScore: 0.9 },
      { name: 'Cebolleta', ref: 'p:cebolleta', quantity: 15, unit: 'g', basis: 'neta', matchScore: 0.92 },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 10, unit: 'ml', basis: 'neta', matchScore: 0.98 },
      { name: 'Zumo de limón', ref: 'p:limon', quantity: 10, unit: 'g', basis: 'neta', matchScore: 0.84 },
      { name: 'Rúcula', ref: 'p:rucula', quantity: 10, unit: 'g', basis: 'neta', matchScore: 0.86 },
    ],
  },

  // ───────────── Arroces ─────────────
  {
    key: 'arroz_negro',
    name: 'Arroz negro',
    kind: 'plato',
    section: 'Arroces',
    description: 'Con sepia y calamar, fumet de roca y alioli. Precio por persona (mínimo 2).',
    menuPrice: 16.5,
    portions: 2,
    unitsSold: 62,
    status: 'revisado',
    tags: ['para compartir', 'sin lactosa'],
    createdDaysAgo: 88,
    procedure:
      'Hacer un fumet con el pescado de roca (30 min). Sofreír la sepia y el calamar, añadir el sofrito de cebolla, pimiento, ajo y tomate, ' +
      'nacarar el arroz, añadir el pimentón y la tinta, y mojar con 3 veces su volumen de fumet. 17 min en paella de 34 cm; reposo 3 min. Servir con alioli.',
    items: [
      { name: 'Arroz bomba', ref: 'p:arroz', quantity: 180, unit: 'g', basis: 'neta' },
      { name: 'Sepia limpia', ref: 'p:sepia', quantity: 250, unit: 'g', basis: 'neta' },
      { name: 'Calamar limpio', ref: 'p:calamar', quantity: 100, unit: 'g', basis: 'neta' },
      { name: 'Tinta de calamar', ref: 'p:tinta', quantity: 2, unit: 'ud', basis: 'neta' },
      { name: 'Pescado de roca (fumet)', ref: 'p:morralla', quantity: 500, unit: 'g', basis: 'bruta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 80, unit: 'g', basis: 'bruta' },
      { name: 'Pimiento verde', ref: 'p:pimiento_verde', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 10, unit: 'g', basis: 'neta' },
      { name: 'Tomate triturado', ref: 'p:tomate_triturado', quantity: 60, unit: 'g', basis: 'neta' },
      { name: 'Pimentón de la Vera dulce', ref: 'p:pimenton_dulce', quantity: 3, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 40, unit: 'ml', basis: 'neta' },
      { name: 'Alioli', ref: 'd:alioli', quantity: 60, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 5, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'paella',
    name: 'Paella de marisco',
    kind: 'plato',
    section: 'Arroces',
    description: 'Gamba roja, mejillón de roca, almejas y calamar sobre fumet de roca. Precio por persona (mínimo 2).',
    menuPrice: 21.0,
    portions: 2,
    unitsSold: 105,
    status: 'revisado',
    tags: ['para compartir', 'sin gluten', 'sin lactosa'],
    createdDaysAgo: 88,
    procedure:
      'Marcar la gamba roja y reservar. Sofreír el calamar, añadir el sofrito y el azafrán tostado, nacarar el arroz y mojar con el fumet hirviendo. ' +
      'A los 10 min incorporar mejillones y almejas, y en los 3 últimos minutos la gamba roja. Reposo de 3 min tapada con un paño.',
    items: [
      { name: 'Arroz bomba', ref: 'p:arroz', quantity: 180, unit: 'g', basis: 'neta' },
      { name: 'Gamba roja', ref: 'p:gamba_roja', quantity: 140, unit: 'g', basis: 'bruta', wastePct: 0, note: 'Se sirve entera, sin merma de pelado (2 piezas por persona)' },
      { name: 'Mejillón de roca', ref: 'p:mejillon', quantity: 200, unit: 'g', basis: 'bruta' },
      { name: 'Almeja japónica', ref: 'p:almeja', quantity: 100, unit: 'g', basis: 'bruta' },
      { name: 'Calamar limpio', ref: 'p:calamar', quantity: 120, unit: 'g', basis: 'neta' },
      { name: 'Pescado de roca (fumet)', ref: 'p:morralla', quantity: 500, unit: 'g', basis: 'bruta' },
      { name: 'Tomate triturado', ref: 'p:tomate_triturado', quantity: 80, unit: 'g', basis: 'neta' },
      { name: 'Pimiento verde', ref: 'p:pimiento_verde', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 10, unit: 'g', basis: 'neta' },
      { name: 'Azafrán en hebra', ref: 'p:azafran', quantity: 0.2, unit: 'g', basis: 'neta' },
      { name: 'Pimentón de la Vera dulce', ref: 'p:pimenton_dulce', quantity: 3, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 50, unit: 'ml', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 5, unit: 'g', basis: 'neta' },
    ],
  },

  // ───────────── Carnes ─────────────
  {
    key: 'chuleton',
    name: 'Chuletón de vaca madurada',
    kind: 'plato',
    section: 'Carnes',
    description: 'Pieza de 1 kg con hueso, madurada 45 días, a la brasa. Con pimientos de Padrón y patatas fritas. Para compartir.',
    menuPrice: 78.0,
    portions: 1,
    unitsSold: 28,
    status: 'revisado',
    tags: ['para compartir', 'sin gluten'],
    createdDaysAgo: 88,
    procedure: 'Atemperar 2 h. Brasa fuerte 4–5 min por lado, reposar 5 min, deshuesar y trinchar en tiras. Sal en escamas al servir.',
    items: [
      { name: 'Chuletón de vaca madurada', ref: 'p:chuleton', quantity: 1, unit: 'kg', basis: 'bruta' },
      { name: 'Pimientos de Padrón', ref: 'p:padron', quantity: 150, unit: 'g', basis: 'bruta' },
      { name: 'Patata agria', ref: 'p:patata', quantity: 300, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de girasol (fritura)', ref: 'p:girasol', quantity: 80, unit: 'ml', basis: 'neta' },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 8, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'solomillo',
    name: 'Solomillo de ternera a la brasa',
    kind: 'plato',
    section: 'Carnes',
    description: '200 g de corazón de solomillo con parmentier de patata y pimientos de Padrón.',
    menuPrice: 34.0,
    portions: 1,
    unitsSold: 30,
    status: 'revisado',
    tags: ['sin gluten'],
    createdDaysAgo: 88,
    procedure: 'Marcar a la brasa y terminar al horno a 180 °C hasta 54 °C en el corazón. Reposar 4 min. Parmentier con mantequilla y leche caliente.',
    items: [
      { name: 'Solomillo de ternera', ref: 'p:solomillo', quantity: 200, unit: 'g', basis: 'cocinada', note: 'Coste según la prueba de rendimiento del solomillo' },
      { name: 'Patata agria', ref: 'p:patata', quantity: 180, unit: 'g', basis: 'bruta' },
      { name: 'Mantequilla', ref: 'p:mantequilla', quantity: 15, unit: 'g', basis: 'neta' },
      { name: 'Leche entera', ref: 'p:leche', quantity: 30, unit: 'ml', basis: 'neta' },
      { name: 'Pimientos de Padrón', ref: 'p:padron', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 10, unit: 'ml', basis: 'neta' },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'secreto',
    name: 'Secreto ibérico',
    kind: 'plato',
    section: 'Carnes',
    description: 'A la brasa, con patatas fritas y pimientos de Padrón.',
    menuPrice: 17.5,
    portions: 1,
    unitsSold: 120,
    status: 'revisado',
    tags: ['sin gluten', 'sin lactosa'],
    createdDaysAgo: 88,
    items: [
      { name: 'Secreto ibérico', ref: 'p:secreto', quantity: 250, unit: 'g', basis: 'bruta' },
      { name: 'Patata agria', ref: 'p:patata', quantity: 200, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de girasol (fritura)', ref: 'p:girasol', quantity: 50, unit: 'ml', basis: 'neta' },
      { name: 'Pimientos de Padrón', ref: 'p:padron', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 3, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'carrilleras',
    name: 'Carrilleras ibéricas al vino tinto',
    kind: 'plato',
    section: 'Carnes',
    description: 'Guisadas 3 horas en su jugo, con parmentier de patata.',
    menuPrice: 17.0,
    portions: 4,
    unitsSold: 115,
    status: 'revisado',
    tags: ['receta de la casa'],
    createdDaysAgo: 88,
    procedure:
      'Salpimentar, enharinar y dorar las carrilleras. Pochar la verdura, desglasar con el vino y reducir a la mitad. Añadir el fondo y las ' +
      'hierbas y guisar 3 h a fuego suave (o 45 min en olla rápida). Triturar la salsa y reducir hasta napar. Receta para 4 raciones.',
    items: [
      { name: 'Carrillera ibérica', ref: 'p:carrillera', quantity: 1.2, unit: 'kg', basis: 'bruta' },
      { name: 'Vino tinto', ref: 'p:vino_tinto', quantity: 500, unit: 'ml', basis: 'neta' },
      { name: 'Fondo oscuro de ternera', ref: 'd:fondo', quantity: 600, unit: 'ml', basis: 'neta' },
      { name: 'Cebolla', ref: 'p:cebolla', quantity: 250, unit: 'g', basis: 'bruta' },
      { name: 'Zanahoria', ref: 'p:zanahoria', quantity: 150, unit: 'g', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 15, unit: 'g', basis: 'neta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 60, unit: 'ml', basis: 'neta' },
      { name: 'Laurel', ref: 'p:laurel', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Pimienta negra', ref: 'p:pimienta', quantity: 1, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 8, unit: 'g', basis: 'neta' },
      { name: 'Patata (parmentier)', ref: 'p:patata', quantity: 600, unit: 'g', basis: 'bruta' },
      { name: 'Mantequilla', ref: 'p:mantequilla', quantity: 60, unit: 'g', basis: 'neta' },
      { name: 'Leche entera', ref: 'p:leche', quantity: 150, unit: 'ml', basis: 'neta' },
    ],
  },

  // ───────────── Pescados ─────────────
  {
    key: 'salmon',
    name: 'Salmón a la plancha',
    kind: 'plato',
    section: 'Pescados',
    description: 'Lomo de salmón con verduras salteadas y limón.',
    menuPrice: 18.5,
    portions: 1,
    unitsSold: 82,
    status: 'revisado',
    tags: ['sin gluten', 'sin lactosa'],
    createdDaysAgo: 88,
    items: [
      { name: 'Salmón', ref: 'p:salmon', quantity: 180, unit: 'g', basis: 'cocinada', note: 'Coste según la prueba de rendimiento del salmón' },
      { name: 'Calabacín', ref: 'p:calabacin', quantity: 80, unit: 'g', basis: 'bruta' },
      { name: 'Pimiento verde', ref: 'p:pimiento_verde', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Zanahoria', ref: 'p:zanahoria', quantity: 50, unit: 'g', basis: 'bruta' },
      { name: 'Cebolleta', ref: 'p:cebolleta', quantity: 40, unit: 'g', basis: 'bruta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 20, unit: 'ml', basis: 'neta' },
      { name: 'Limón', ref: 'p:limon', quantity: 20, unit: 'g', basis: 'bruta' },
      { name: 'Sal en escamas', ref: 'p:sal_escamas', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'merluza',
    name: 'Merluza en salsa verde',
    kind: 'plato',
    section: 'Pescados',
    description: 'Lomo de merluza de pincho con almejas, guisantes y perejil.',
    menuPrice: 22.0,
    portions: 1,
    unitsSold: 40,
    status: 'revisado',
    tags: ['receta de la casa'],
    createdDaysAgo: 88,
    procedure:
      'Dorar el ajo en el aceite, añadir la harina y el vino, y mojar con fumet de las espinas. Cocer la merluza en la salsa 4 min por lado ' +
      'moviendo la cazuela para ligar; abrir las almejas en la misma salsa y terminar con perejil y guisantes.',
    items: [
      { name: 'Merluza de pincho', ref: 'p:merluza', quantity: 180, unit: 'g', basis: 'neta' },
      { name: 'Almeja japónica', ref: 'p:almeja', quantity: 100, unit: 'g', basis: 'bruta' },
      { name: 'Pescado de roca (fumet)', ref: 'p:morralla', quantity: 150, unit: 'g', basis: 'bruta' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 10, unit: 'g', basis: 'neta' },
      { name: 'Perejil', ref: 'p:perejil', quantity: 10, unit: 'g', basis: 'neta' },
      { name: 'Vino blanco', ref: 'p:vino_blanco', quantity: 50, unit: 'ml', basis: 'neta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 10, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 40, unit: 'ml', basis: 'neta' },
      { name: 'Guisantes', ref: 'p:guisantes', quantity: 20, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'bacalao',
    name: 'Bacalao al pil pil',
    kind: 'plato',
    section: 'Pescados',
    description: 'Lomo de bacalao confitado y emulsionado con su gelatina, ajo y guindilla.',
    menuPrice: 22.0,
    portions: 1,
    unitsSold: 33,
    status: 'revisado',
    tags: ['sin gluten', 'sin lactosa'],
    createdDaysAgo: 88,
    procedure: 'Confitar el bacalao con la piel hacia arriba a 60 °C en el aceite aromatizado con ajo y guindilla. Retirar y ligar el pil pil con movimientos de vaivén.',
    items: [
      { name: 'Lomo de bacalao desalado', ref: 'p:bacalao', quantity: 220, unit: 'g', basis: 'neta' },
      { name: 'Aceite de oliva virgen extra', ref: 'p:aove', quantity: 120, unit: 'ml', basis: 'neta', note: 'Aceite consumido en el confitado y la emulsión' },
      { name: 'Ajo', ref: 'p:ajo', quantity: 15, unit: 'g', basis: 'neta' },
      { name: 'Guindilla cayena', ref: 'p:cayena', quantity: 1, unit: 'g', basis: 'neta' },
    ],
  },

  // ───────────── Postres ─────────────
  {
    key: 'tarta_queso',
    name: 'Tarta de queso',
    kind: 'plato',
    section: 'Postres',
    description: 'Cremosa, al horno, con un toque de queso azul de Valdeón.',
    menuPrice: 7.0,
    portions: 10,
    unitsSold: 150,
    status: 'revisado',
    tags: ['receta de la casa'],
    createdDaysAgo: 88,
    procedure:
      'Batir el queso crema con el azúcar, añadir los huevos uno a uno, la nata, el queso azul fundido, la harina tamizada y la sal. ' +
      'Hornear a 210 °C 30 min en molde de 24 cm forrado con papel. Enfriar 12 h en cámara. 10 raciones.',
    items: [
      { name: 'Queso crema', ref: 'p:queso_crema', quantity: 1, unit: 'kg', basis: 'neta' },
      { name: 'Queso azul', ref: 'p:queso_azul', quantity: 80, unit: 'g', basis: 'neta' },
      { name: 'Nata 35 %', ref: 'p:nata', quantity: 500, unit: 'ml', basis: 'neta' },
      { name: 'Huevos', ref: 'p:huevos', quantity: 6, unit: 'ud', basis: 'bruta' },
      { name: 'Azúcar', ref: 'p:azucar', quantity: 250, unit: 'g', basis: 'neta' },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 30, unit: 'g', basis: 'neta' },
      { name: 'Sal', ref: 'p:sal', quantity: 2, unit: 'g', basis: 'neta' },
    ],
  },
  {
    key: 'torrija',
    name: 'Torrija caramelizada',
    kind: 'plato',
    section: 'Postres',
    description: 'De pan brioche, caramelizada al momento, con helado de vainilla.',
    menuPrice: 6.0,
    portions: 8,
    unitsSold: 50,
    status: 'revisado',
    createdDaysAgo: 88,
    procedure:
      'Infusionar la leche y la nata con la canela, la piel de limón y parte del azúcar. Empapar las rebanadas de brioche 12 h. Pasar por huevo, ' +
      'dorar en mantequilla y caramelizar con azúcar y soplete. Servir con una bola de helado. 8 raciones por barra.',
    items: [
      { name: 'Pan brioche', ref: 'p:brioche', quantity: 1, unit: 'ud', basis: 'bruta' },
      { name: 'Leche entera', ref: 'p:leche', quantity: 750, unit: 'ml', basis: 'neta' },
      { name: 'Nata 35 %', ref: 'p:nata', quantity: 250, unit: 'ml', basis: 'neta' },
      { name: 'Azúcar', ref: 'p:azucar', quantity: 230, unit: 'g', basis: 'neta' },
      { name: 'Huevos', ref: 'p:huevos', quantity: 3, unit: 'ud', basis: 'bruta' },
      { name: 'Mantequilla', ref: 'p:mantequilla', quantity: 60, unit: 'g', basis: 'neta' },
      { name: 'Canela', ref: 'p:canela', quantity: 2, unit: 'g', basis: 'neta' },
      { name: 'Limón (piel)', ref: 'p:limon', quantity: 60, unit: 'g', basis: 'bruta' },
      { name: 'Helado de vainilla', ref: 'p:helado_vainilla', quantity: 480, unit: 'ml', basis: 'neta', note: 'Una bola de 60 ml por ración' },
    ],
  },
  {
    key: 'coulant',
    name: 'Coulant de chocolate',
    kind: 'plato',
    section: 'Postres',
    description: 'Corazón fundente de chocolate 70 %, helado de vainilla y frambuesas.',
    menuPrice: 7.5,
    portions: 8,
    unitsSold: 30,
    status: 'borrador',
    createdDaysAgo: 3,
    notes: 'Plato nuevo leído de la carta. Receta propuesta por la base de recetas local: revisa los gramajes antes de confirmar.',
    items: [
      { name: 'Chocolate negro 70 %', ref: 'p:chocolate', quantity: 250, unit: 'g', basis: 'neta', matchScore: 0.9 },
      { name: 'Mantequilla', ref: 'p:mantequilla', quantity: 200, unit: 'g', basis: 'neta', matchScore: 1 },
      { name: 'Huevos', ref: 'p:huevos', quantity: 5, unit: 'ud', basis: 'bruta', matchScore: 0.96 },
      { name: 'Azúcar', ref: 'p:azucar', quantity: 150, unit: 'g', basis: 'neta', matchScore: 0.95 },
      { name: 'Harina de trigo', ref: 'p:harina', quantity: 60, unit: 'g', basis: 'neta', matchScore: 0.97 },
      { name: 'Helado de vainilla', ref: 'p:helado_vainilla', quantity: 480, unit: 'ml', basis: 'neta', matchScore: 0.93 },
      { name: 'Frambuesas', ref: 'p:frambuesa', quantity: 160, unit: 'g', basis: 'bruta', matchScore: 0.89 },
    ],
  },
];
