'use strict';
// Batería de frases reales de repesca con la respuesta correcta. Referencia: martes 29-sep-2026 a
// las 10:00 en Boadilla. Festivos: 5-oct (local), 12-oct, 2-nov, 7 y 8-dic, 25-dic y 1 y 6-ene.
// La clínica abre de lunes a viernes de 11 a 20 y los sábados de 10 a 20.
//
// «intencion» es lo que se entiende; «fecha» es cuándo se vuelve a escribir (si toca).
// Cuando la clínica pase sus conversaciones reales, se añaden aquí (sin datos personales).

module.exports = [
  // ── Aplazamientos: la fecha la pone el código ────────────────────────────────────────────
  { frase: 'El mes que viene me viene mejor', intencion: 'aplazar', plazo: 'mes_siguiente', fecha: '2026-10-06' },
  { frase: 'el mes q viene mejor, ahora imposible', intencion: 'aplazar', plazo: 'mes_siguiente', fecha: '2026-10-06' },
  { frase: 'Mejor la semana que viene', intencion: 'aplazar', plazo: 'semana_siguiente', fecha: '2026-10-06' },
  { frase: 'Esta semana imposible', intencion: 'aplazar', plazo: 'semana_siguiente', fecha: '2026-10-06' },
  { frase: 'Llámame la semana que viene por la tarde', intencion: 'aplazar', plazo: 'semana_siguiente', fecha: '2026-10-06', hora: '17:30' },
  { frase: 'Escríbeme en dos semanas', intencion: 'aplazar', plazo: 'semanas', fecha: '2026-10-13' },
  { frase: 'Dentro de 10 días hablamos', intencion: 'aplazar', plazo: 'dias', fecha: '2026-10-09' },
  { frase: 'En quince días te digo', intencion: 'aplazar', plazo: 'dias', fecha: '2026-10-14' },
  { frase: 'Te digo algo en unos días', intencion: 'aplazar', plazo: 'dias', fecha: '2026-10-03' },
  { frase: 'En un par de meses', intencion: 'aplazar', plazo: 'meses', fecha: '2026-11-30' },
  { frase: 'Después del verano', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-09-06' },
  { frase: 'Lo dejo para después del verano', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-09-06' },
  { frase: 'Después de Navidad', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-01-11' },
  { frase: 'Pasadas las navidades mejor', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-01-11' },
  { frase: 'Después de Reyes', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-01-11' },
  { frase: 'No puedo hasta el año que viene', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-01-11' },
  { frase: 'Después de Semana Santa', intencion: 'aplazar', plazo: 'tras_hito', fecha: '2027-03-30' },
  { frase: 'En enero', intencion: 'aplazar', plazo: 'mes', fecha: '2027-01-04' },
  { frase: 'Hasta enero no puedo', intencion: 'aplazar', plazo: 'mes', fecha: '2027-01-04' },
  { frase: 'Vale, pues en enero hablamos', intencion: 'aplazar', plazo: 'mes', fecha: '2027-01-04' },
  { frase: 'En octubre mejor', intencion: 'aplazar', plazo: 'mes', fecha: '2026-10-06' },
  { frase: 'En noviembre', intencion: 'aplazar', plazo: 'mes', fecha: '2026-11-03' },
  { frase: 'Para diciembre', intencion: 'aplazar', plazo: 'mes', fecha: '2026-12-09' },
  { frase: 'Escríbeme en diciembre por la mañana', intencion: 'aplazar', plazo: 'mes', fecha: '2026-12-09', hora: '11:30' },
  { frase: 'Vuelvo de viaje el 20', intencion: 'aplazar', plazo: 'tras_fecha', fecha: '2026-10-21' },
  { frase: 'Hasta el 15 de octubre estoy fuera', intencion: 'aplazar', plazo: 'tras_fecha', fecha: '2026-10-16' },
  { frase: 'Estoy de vacaciones hasta el 12 de octubre', intencion: 'aplazar', plazo: 'tras_fecha', fecha: '2026-10-13' },
  { frase: 'Estoy fuera de Madrid hasta finales de octubre', intencion: 'aplazar', plazo: 'tras_fecha', fecha: '2026-10-26' },
  { frase: 'A partir del 20', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-10-20' },
  { frase: 'El día 15', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-10-15' },
  { frase: 'El 3 de noviembre', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-11-03' },
  { frase: 'A principios de noviembre', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-11-03' },
  { frase: 'A mediados de octubre', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-10-15' },
  { frase: 'A principios del mes que viene', intencion: 'aplazar', plazo: 'inicio_mes', fecha: '2026-10-01' },
  { frase: 'A final de mes', intencion: 'aplazar', plazo: 'fin_mes', fecha: '2026-10-01' },
  { frase: 'Cuando cobre', intencion: 'aplazar', plazo: 'cobro', fecha: '2026-10-01' },
  { frase: 'Cuando cobre, que cobro el 5', intencion: 'aplazar', plazo: 'cobro', fecha: '2026-10-06' },
  { frase: 'Cuando tenga dinero te digo', intencion: 'aplazar', plazo: 'cobro', fecha: '2026-10-01' },
  { frase: 'Cuando me paguen la nómina', intencion: 'aplazar', plazo: 'cobro', fecha: '2026-10-01' },
  { frase: 'Este mes no puedo', intencion: 'aplazar', plazo: 'mes_siguiente', fecha: '2026-10-06' },
  { frase: 'Después del puente', intencion: 'aplazar', plazo: 'dias', fecha: '2026-10-06' },
  { frase: 'El jueves', intencion: 'aplazar', plazo: 'dia_semana', fecha: '2026-10-01' },
  { frase: 'El lunes', intencion: 'aplazar', plazo: 'dia_semana', fecha: '2026-10-06' },
  { frase: 'El domingo', intencion: 'aplazar', plazo: 'dia_semana', fecha: '2026-10-06' },
  { frase: 'El viernes de la semana que viene', intencion: 'aplazar', plazo: 'dia_semana', fecha: '2026-10-09' },
  { frase: 'El lunes no, mejor el miércoles', intencion: 'aplazar', plazo: 'dia_semana', fecha: '2026-09-30' },
  { frase: 'Mañana te digo', intencion: 'aplazar', plazo: 'manana', fecha: '2026-09-30' },
  { frase: 'Pasado mañana', intencion: 'aplazar', plazo: 'pasado_manana', fecha: '2026-10-01' },
  { frase: 'Hoy no puedo', intencion: 'aplazar', plazo: 'manana', fecha: '2026-09-30' },
  { frase: 'Más adelante', intencion: 'aplazar', plazo: 'vago', fecha: '2026-10-13' },
  { frase: 'Ya te diré', intencion: 'aplazar', plazo: 'vago', fecha: '2026-10-13' },
  { frase: 'No es el momento', intencion: 'aplazar', plazo: 'vago', fecha: '2026-10-13' },
  { frase: 'Te escribo yo cuando pueda', intencion: 'aplazar', plazo: 'vago', fecha: '2026-10-13' },
  { frase: 'Ahora no me viene bien, más adelante', intencion: 'aplazar', plazo: 'vago', fecha: '2026-10-13' },
  { frase: 'En unos meses', intencion: 'aplazar', plazo: 'meses', fecha: '2026-12-29' },

  // ── Ocupado ahora: el único caso en que se escribe «luego» o «mañana» ────────────────────
  { frase: 'Ahora no puedo, estoy trabajando', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29', hora: '18:00' },
  { frase: 'Ahora mismo estoy conduciendo', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29', hora: '18:00' },
  { frase: 'Estoy liada con los niños, luego te escribo', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29' },
  { frase: 'Esta tarde te digo', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29' },
  { frase: 'Me pillas en mal momento', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29' },
  { frase: 'Estoy en una reunión', intencion: 'ocupado_ahora', plazo: 'hoy_tarde', fecha: '2026-09-29' },

  // ── Precio ───────────────────────────────────────────────────────────────────────────────
  { frase: 'Me parece muy caro', intencion: 'precio' },
  { frase: 'Es carísimo', intencion: 'precio' },
  { frase: 'Uf, un poco cara la verdad', intencion: 'precio' },
  { frase: 'No me lo puedo permitir ahora mismo', intencion: 'precio' },
  { frase: 'Se me va de presupuesto', intencion: 'precio' },
  { frase: 'Mi pareja dice que es mucho dinero', intencion: 'precio' },
  { frase: 'Estoy en paro ahora', intencion: 'precio' },
  { frase: 'He tenido muchos gastos', intencion: 'precio' },
  { frase: 'Ando justa este mes', intencion: 'precio' },
  { frase: 'En otra clínica me lo hacen más barato', intencion: 'competencia_precio' },
  { frase: 'He visto ofertas mejores', intencion: 'competencia_precio' },
  { frase: 'Me han dado mejor precio en otro sitio', intencion: 'competencia_precio' },

  // ── Pensar y dudas ───────────────────────────────────────────────────────────────────────
  { frase: 'Lo tengo que pensar', intencion: 'pensar' },
  { frase: 'Me lo pienso y te digo', intencion: 'pensar' },
  { frase: 'Lo hablo con mi marido y te digo', intencion: 'pensar' },
  { frase: 'Lo consulto', intencion: 'pensar' },
  { frase: 'No lo tengo claro', intencion: 'pensar' },
  { frase: 'Tengo que mirar mi agenda', intencion: 'pensar' },
  { frase: 'Déjame que lo mire', intencion: 'pensar' },
  { frase: 'Estoy mirando otras clínicas', intencion: 'pensar' },
  { frase: '¿Duele?', intencion: 'duda_medica' },
  { frase: 'Me da miedo', intencion: 'duda_medica' },
  { frase: 'Es que me da mucho respeto', intencion: 'duda_medica' },
  { frase: '¿Tiene riesgos?', intencion: 'duda_medica' },
  { frase: '¿Y cuánto tiempo de recuperación tiene?', intencion: 'duda_medica' },
  { frase: '¿Se nota mucho después?', intencion: 'duda_medica' },

  // ── Salud: siempre a una persona (y urgente si parece una complicación) ─────────────────
  { frase: 'Estoy embarazada', intencion: 'salud_personal' },
  { frase: 'Estoy dando el pecho todavía', intencion: 'salud_personal' },
  { frase: 'Tomo Sintrom', intencion: 'salud_personal' },
  { frase: 'Estoy tomando antibióticos, ¿puedo ponerme bótox?', intencion: 'salud_personal' },
  { frase: 'Tengo alergia a la lidocaína', intencion: 'salud_personal' },
  { frase: 'Cuando me recupere de la operación', intencion: 'salud_personal' },
  { frase: 'Mi médico me ha dicho que espere', intencion: 'salud_personal' },
  { frase: 'Me ha salido un bulto en el labio después del relleno', intencion: 'salud_personal', urgente: true },
  { frase: 'Sigo muy hinchada desde ayer y me duele mucho', intencion: 'salud_personal', urgente: true },
  { frase: 'Tengo fiebre desde el tratamiento', intencion: 'salud_personal', urgente: true },

  // ── Cierres y bajas ──────────────────────────────────────────────────────────────────────
  { frase: 'Ya me lo hice en otra clínica', intencion: 'ya_hecho' },
  { frase: 'Ya me lo he hecho, gracias', intencion: 'ya_hecho' },
  { frase: 'No me interesa, gracias', intencion: 'no_interesa' },
  { frase: 'No, gracias', intencion: 'no_interesa' },
  { frase: 'Ya no lo necesito', intencion: 'no_interesa' },
  { frase: 'He cambiado de opinión', intencion: 'no_interesa' },
  { frase: 'No me escribáis más', intencion: 'baja' },
  { frase: 'BAJA', intencion: 'baja' },
  { frase: 'Stop', intencion: 'baja' },
  { frase: 'Dejad de mandarme mensajes', intencion: 'baja' },
  { frase: 'Borrad mis datos por favor', intencion: 'baja' },
  { frase: 'No quiero recibir más mensajes', intencion: 'baja' },
  { frase: 'Quitadme de vuestra lista', intencion: 'baja' },
  { frase: 'Fatal, nadie me contesta nunca', intencion: 'queja' },
  { frase: 'Quiero poner una reclamación', intencion: 'queja' },
  { frase: 'Esto es un timo', intencion: 'queja' },
  // «último» contiene «timo»: no es una queja.
  { frase: 'El último día de octubre me viene bien', intencion: 'aplazar', plazo: 'fecha', fecha: '2026-10-31' },

  // ── Quiere cita o pregunta ───────────────────────────────────────────────────────────────
  { frase: 'Vale, dame cita', intencion: 'reservar' },
  { frase: 'Sí, búscame hueco', intencion: 'reservar' },
  { frase: '¿Tenéis hueco el jueves por la tarde?', intencion: 'reservar', plazo: 'dia_semana' },
  { frase: 'Quiero pedir cita para el martes', intencion: 'reservar', plazo: 'dia_semana' },
  { frase: 'Perfecto, reserva el martes a las 5', intencion: 'reservar', plazo: 'dia_semana' },
  { frase: 'Tengo una boda el 20 y quiero estar guapa', intencion: 'evento', plazo: 'fecha' },
  { frase: 'Quiero estar perfecta para la comunión de mi hija', intencion: 'evento' },
  { frase: '¿Cuánto cuesta el relleno de labios?', intencion: 'pregunta' },
  { frase: '¿Qué incluye el precio?', intencion: 'pregunta' },
  { frase: '¿Hacéis financiación?', intencion: 'pregunta' },
  { frase: '¿Se puede pagar a plazos?', intencion: 'pregunta' },
  { frase: 'Mándame información', intencion: 'pregunta' },
  { frase: '¿Qué horario tenéis?', intencion: 'pregunta' },
  { frase: 'Me viene mejor por las tardes', intencion: 'preferencia_horario' },
  { frase: 'Sí', intencion: 'acepta' },
  { frase: 'Ok', intencion: 'acepta' },
];
