-- 001 · Base de la clínica: datos, horario, festivos, salas, equipos, profesionales, catálogo de
-- tratamientos, pacientes, consentimientos, personal de la app, registro de hechos, cola y candados.
--
-- PostgreSQL (el de Supabase y el del portátil). Lo que viene de la época de MariaDB, y cómo queda:
--   · Todas las fechas y horas son TIMESTAMPTZ: instantes absolutos, que db.js manda y lee en UTC (la
--     hora de Madrid se calcula en el motor). Un día suelto es DATE y la hora del reloj, TIME.
--   · Los ENUM son TEXT con un CHECK (col IN (…)); un valor nuevo se añade cambiando ese CHECK.
--   · El JSON es TEXT con un CHECK de que es JSON válido, igual que era en MariaDB; db.js lo devuelve
--     como texto y el código hace JSON.parse.
--   · Los UNSIGNED llevan CHECK (col >= 0) donde importa (contadores, duraciones, intentos).
--   · Los ids son GENERATED BY DEFAULT AS IDENTITY: se pueden poner a mano (las semillas y las pruebas
--     lo hacen) y, como el AUTO_INCREMENT de MariaDB, el siguiente salta por encima del mayor que se
--     puso (avanzar_identidad, abajo).
--   · MariaDB comparaba texto sin distinguir mayúsculas ni tildes; PostgreSQL sí las distingue. Qué se
--     hace con cada columna (emails con lower(), códigos exactos…): docs/PORTE-POSTGRES.md.
--   · Los índices llevan un nombre único en todo el esquema (en PostgreSQL comparten espacio con las
--     tablas). MariaDB creaba sola un índice por cada clave ajena; aquí van escritos, con el sufijo _idx.

-- ON UPDATE CURRENT_TIMESTAMP de MariaDB: actualizado_en se pone a la hora de la transacción cuando
-- cambia cualquier otra columna de la fila (si el UPDATE no cambia nada, o él mismo fija
-- actualizado_en, se deja como está). Las pruebas la sustituyen por la del reloj falso (test/ayuda-bd.js).
CREATE OR REPLACE FUNCTION set_actualizado_en() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.actualizado_en IS NOT DISTINCT FROM OLD.actualizado_en AND ROW(NEW.*) IS DISTINCT FROM ROW(OLD.*) THEN
    NEW.actualizado_en := now();
  END IF;
  RETURN NEW;
END
$$;

-- El AUTO_INCREMENT de MariaDB salta por encima de un id puesto a mano; la identidad de PostgreSQL no
-- (el siguiente id automático chocaría con el que se puso). Este disparador, uno por tabla con
-- identidad, y por sentencia (no por fila), sube la secuencia hasta el mayor id insertado.
CREATE OR REPLACE FUNCTION avanzar_identidad() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  secuencia regclass := pg_get_serial_sequence(format('%I.%I', TG_TABLE_SCHEMA, TG_TABLE_NAME), 'id')::regclass;
  mayor bigint;
BEGIN
  SELECT max(id) INTO mayor FROM nuevas;
  IF mayor IS NOT NULL AND mayor > COALESCE(pg_sequence_last_value(secuencia), 0) THEN
    PERFORM setval(secuencia, mayor);
  END IF;
  RETURN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS clinica (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  nombre VARCHAR(120) NOT NULL,
  nombre_corto VARCHAR(40) NOT NULL,
  razon_social VARCHAR(160),
  nif VARCHAR(20),
  direccion VARCHAR(200),
  cp VARCHAR(10),
  municipio VARCHAR(80),
  provincia VARCHAR(80),
  telefono VARCHAR(20),
  whatsapp VARCHAR(20),
  email VARCHAR(160),
  web VARCHAR(160),
  zona_horaria VARCHAR(40) NOT NULL DEFAULT 'Europe/Madrid',
  lat NUMERIC(9,6),
  lng NUMERIC(9,6),
  google_place_id VARCHAR(120),
  paso_agenda_min SMALLINT NOT NULL DEFAULT 5,
  retencion_hueco_min INTEGER NOT NULL DEFAULT 15,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT clinica_paso_agenda_min_pos CHECK (paso_agenda_min >= 0),
  CONSTRAINT clinica_retencion_hueco_min_pos CHECK (retencion_hueco_min >= 0),
  CONSTRAINT clinica_una_fila CHECK (id = 1)
);
CREATE OR REPLACE TRIGGER clinica_actualizado BEFORE UPDATE ON clinica FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- Horario de apertura por día de la semana (1 = lunes … 7 = domingo). Varias filas = jornada partida.
CREATE TABLE IF NOT EXISTS horario_clinica (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia_semana SMALLINT NOT NULL,
  abre TIME NOT NULL,
  cierra TIME NOT NULL,
  CONSTRAINT horario_dia CHECK (dia_semana BETWEEN 1 AND 7),
  CONSTRAINT horario_orden CHECK (abre < cierra)
);
CREATE UNIQUE INDEX IF NOT EXISTS horario_unico ON horario_clinica (dia_semana, abre);
CREATE OR REPLACE TRIGGER horario_clinica_avanzar_id AFTER INSERT ON horario_clinica REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS festivos (
  fecha DATE PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  ambito TEXT NOT NULL,
  CONSTRAINT festivos_ambito_chk CHECK (ambito IN ('nacional','autonomico','local','clinica'))
);

-- Cierres puntuales de toda la clínica (obras, formación, vacaciones).
CREATE TABLE IF NOT EXISTS cierres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  desde TIMESTAMPTZ NOT NULL,
  hasta TIMESTAMPTZ NOT NULL,
  motivo VARCHAR(160) NOT NULL,
  CONSTRAINT cierre_orden CHECK (desde < hasta)
);
CREATE OR REPLACE TRIGGER cierres_avanzar_id AFTER INSERT ON cierres REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS salas (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  nombre VARCHAR(80) NOT NULL,
  tipo TEXT NOT NULL,
  color CHAR(7),
  orden SMALLINT NOT NULL DEFAULT 0,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  notas VARCHAR(255),
  CONSTRAINT salas_tipo_chk CHECK (tipo IN ('consulta_medica','cabina_estetica','cabina_aparatologia','quirofano','sala_capilar','head_spa','otra'))
);
CREATE UNIQUE INDEX IF NOT EXISTS salas_codigo ON salas (codigo);
CREATE OR REPLACE TRIGGER salas_avanzar_id AFTER INSERT ON salas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Aparatos. Si sala_id está puesto, el aparato vive en esa sala; si movil = TRUE, se puede llevar a
-- otra. unidades > 1 cuando hay varios iguales.
CREATE TABLE IF NOT EXISTS equipos (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  nombre VARCHAR(80) NOT NULL,
  tipo VARCHAR(60),
  sala_id SMALLINT,
  movil BOOLEAN NOT NULL DEFAULT FALSE,
  unidades SMALLINT NOT NULL DEFAULT 1,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  confirmado BOOLEAN NOT NULL DEFAULT FALSE,
  notas VARCHAR(255),
  CONSTRAINT equipos_unidades_pos CHECK (unidades >= 0),
  CONSTRAINT equipo_sala FOREIGN KEY (sala_id) REFERENCES salas (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS equipos_codigo ON equipos (codigo);
CREATE INDEX IF NOT EXISTS equipo_sala_idx ON equipos (sala_id);
CREATE OR REPLACE TRIGGER equipos_avanzar_id AFTER INSERT ON equipos REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS profesionales (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  rol TEXT NOT NULL,
  especialidad VARCHAR(160),
  color CHAR(7),
  email VARCHAR(160),
  telefono VARCHAR(20),
  orden SMALLINT NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  confirmado BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT profesionales_rol_chk CHECK (rol IN ('medico','cirujano','enfermeria','esteticista','nutricionista','tricologo','recepcion','otro'))
);
CREATE UNIQUE INDEX IF NOT EXISTS profesionales_codigo ON profesionales (codigo);
CREATE OR REPLACE TRIGGER profesionales_avanzar_id AFTER INSERT ON profesionales REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS profesional_horarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profesional_id SMALLINT NOT NULL,
  dia_semana SMALLINT NOT NULL,
  inicio TIME NOT NULL,
  fin TIME NOT NULL,
  sala_preferida_id SMALLINT,
  vigente_desde DATE,
  vigente_hasta DATE,
  CONSTRAINT ph_dia CHECK (dia_semana BETWEEN 1 AND 7),
  CONSTRAINT ph_orden CHECK (inicio < fin),
  CONSTRAINT ph_profesional FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE CASCADE,
  CONSTRAINT ph_sala FOREIGN KEY (sala_preferida_id) REFERENCES salas (id)
);
CREATE INDEX IF NOT EXISTS ph_profesional_idx ON profesional_horarios (profesional_id);
CREATE INDEX IF NOT EXISTS ph_sala_idx ON profesional_horarios (sala_preferida_id);
CREATE OR REPLACE TRIGGER profesional_horarios_avanzar_id AFTER INSERT ON profesional_horarios REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS profesional_ausencias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profesional_id SMALLINT NOT NULL,
  desde TIMESTAMPTZ NOT NULL,
  hasta TIMESTAMPTZ NOT NULL,
  motivo VARCHAR(160),
  CONSTRAINT pa_orden CHECK (desde < hasta),
  CONSTRAINT pa_profesional FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS pa_rango ON profesional_ausencias (profesional_id, desde, hasta);
CREATE OR REPLACE TRIGGER profesional_ausencias_avanzar_id AFTER INSERT ON profesional_ausencias REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Comidas y descansos. «fija»: de ventana_inicio a ventana_fin. «flotante»: duracion_min dentro de
-- la ventana; el motor de agenda garantiza que siempre quepa. dia_semana NULL = todos los días.
CREATE TABLE IF NOT EXISTS pausas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profesional_id SMALLINT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'comida',
  modo TEXT NOT NULL,
  dia_semana SMALLINT,
  ventana_inicio TIME NOT NULL,
  ventana_fin TIME NOT NULL,
  duracion_min INTEGER NOT NULL,
  CONSTRAINT pausas_tipo_chk CHECK (tipo IN ('comida','descanso')),
  CONSTRAINT pausas_modo_chk CHECK (modo IN ('fija','flotante')),
  CONSTRAINT pausas_dia_semana_pos CHECK (dia_semana >= 0),
  CONSTRAINT pausas_duracion_min_pos CHECK (duracion_min >= 0),
  CONSTRAINT pausa_orden CHECK (ventana_inicio < ventana_fin),
  CONSTRAINT pausa_profesional FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS pausa_profesional_idx ON pausas (profesional_id);
CREATE OR REPLACE TRIGGER pausas_avanzar_id AFTER INSERT ON pausas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS familias (
  codigo VARCHAR(40) PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  orden SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tratamientos (
  id VARCHAR(80) PRIMARY KEY,
  nombre VARCHAR(160) NOT NULL,
  familia VARCHAR(40) NOT NULL,
  subfamilia VARCHAR(80),
  descripcion VARCHAR(400),
  duracion_min INTEGER NOT NULL,
  duracion_fuente TEXT NOT NULL DEFAULT 'estimada',
  primera_visita_min INTEGER,
  holgura_antes_min INTEGER NOT NULL DEFAULT 0,
  holgura_despues_min INTEGER NOT NULL DEFAULT 10,
  crema_anestesica_min INTEGER NOT NULL DEFAULT 0,
  precio_eur NUMERIC(9,2),
  precio_texto VARCHAR(80),
  es_promocion BOOLEAN NOT NULL DEFAULT FALSE,
  rol_profesional TEXT,
  sala_tipo TEXT,
  equipo_codigo VARCHAR(40),
  sesiones VARCHAR(80),
  intervalo_sesiones_dias INTEGER,
  repetir_cada_dias INTEGER,
  repetir_fuente VARCHAR(40),
  regimen_legal TEXT NOT NULL DEFAULT 'desconocido',
  publicidad_restringida BOOLEAN NOT NULL DEFAULT FALSE,
  motivo_restriccion VARCHAR(255),
  texto_whatsapp VARCHAR(400),
  alias TEXT,
  fuentes TEXT,
  notas VARCHAR(600),
  reservable_ia BOOLEAN NOT NULL DEFAULT TRUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  validado_clinica BOOLEAN NOT NULL DEFAULT FALSE,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT tratamientos_duracion_min_pos CHECK (duracion_min >= 0),
  CONSTRAINT tratamientos_duracion_fuente_chk CHECK (duracion_fuente IN ('clinica','treatwell','web','sector','estimada')),
  CONSTRAINT tratamientos_primera_visita_min_pos CHECK (primera_visita_min >= 0),
  CONSTRAINT tratamientos_holgura_antes_min_pos CHECK (holgura_antes_min >= 0),
  CONSTRAINT tratamientos_holgura_despues_min_pos CHECK (holgura_despues_min >= 0),
  CONSTRAINT tratamientos_crema_anestesica_min_pos CHECK (crema_anestesica_min >= 0),
  CONSTRAINT tratamientos_rol_profesional_chk CHECK (rol_profesional IN ('medico','cirujano','enfermeria','esteticista','nutricionista','tricologo','recepcion','otro')),
  CONSTRAINT tratamientos_sala_tipo_chk CHECK (sala_tipo IN ('consulta_medica','cabina_estetica','cabina_aparatologia','quirofano','sala_capilar','head_spa','otra')),
  CONSTRAINT tratamientos_intervalo_sesiones_dias_pos CHECK (intervalo_sesiones_dias >= 0),
  CONSTRAINT tratamientos_repetir_cada_dias_pos CHECK (repetir_cada_dias >= 0),
  CONSTRAINT tratamientos_regimen_legal_chk CHECK (regimen_legal IN ('medicamento_receta','producto_sanitario','aparatologia','cirugia','cosmetico','servicio','desconocido')),
  CONSTRAINT tratamientos_alias_json CHECK (alias IS NULL OR alias::jsonb IS NOT NULL),
  CONSTRAINT tratamientos_fuentes_json CHECK (fuentes IS NULL OR fuentes::jsonb IS NOT NULL),
  CONSTRAINT trat_familia FOREIGN KEY (familia) REFERENCES familias (codigo)
);
CREATE INDEX IF NOT EXISTS trat_familia_idx ON tratamientos (familia, activo);
CREATE OR REPLACE TRIGGER tratamientos_actualizado BEFORE UPDATE ON tratamientos FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- Salas y profesionales permitidos por tratamiento. Si un tratamiento no tiene filas aquí, vale
-- cualquier sala de su sala_tipo y cualquier profesional de su rol.
CREATE TABLE IF NOT EXISTS tratamiento_salas (
  tratamiento_id VARCHAR(80) NOT NULL,
  sala_id SMALLINT NOT NULL,
  PRIMARY KEY (tratamiento_id, sala_id),
  CONSTRAINT ts_trat FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id) ON DELETE CASCADE,
  CONSTRAINT ts_sala FOREIGN KEY (sala_id) REFERENCES salas (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ts_sala_idx ON tratamiento_salas (sala_id);

CREATE TABLE IF NOT EXISTS tratamiento_profesionales (
  tratamiento_id VARCHAR(80) NOT NULL,
  profesional_id SMALLINT NOT NULL,
  PRIMARY KEY (tratamiento_id, profesional_id),
  CONSTRAINT tp_trat FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id) ON DELETE CASCADE,
  CONSTRAINT tp_prof FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS tp_prof_idx ON tratamiento_profesionales (profesional_id);

-- Respuestas a dudas frecuentes. Salen del blog de la clínica y solo las usa la IA cuando el
-- equipo médico las ha aprobado.
CREATE TABLE IF NOT EXISTS respuestas_aprobadas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tratamiento_id VARCHAR(80),
  pregunta VARCHAR(255) NOT NULL,
  respuesta VARCHAR(800) NOT NULL,
  fuente_url VARCHAR(255),
  aprobada BOOLEAN NOT NULL DEFAULT FALSE,
  aprobada_por VARCHAR(120),
  aprobada_en TIMESTAMPTZ,
  CONSTRAINT ra_trat FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ra_trat_idx ON respuestas_aprobadas (tratamiento_id);
CREATE OR REPLACE TRIGGER respuestas_aprobadas_avanzar_id AFTER INSERT ON respuestas_aprobadas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS pacientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellidos VARCHAR(120),
  telefono VARCHAR(20),
  email VARCHAR(160),
  fecha_nacimiento DATE,
  idioma CHAR(2) NOT NULL DEFAULT 'es',
  origen VARCHAR(40),
  horario_preferido VARCHAR(60),
  hora_habitual_respuesta TIME,
  ghl_contact_id VARCHAR(60),
  flowww_id VARCHAR(60),
  notas_cifradas BYTEA,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  anonimizado_en TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS paciente_telefono ON pacientes (telefono);
CREATE INDEX IF NOT EXISTS paciente_email ON pacientes (lower(email));
CREATE OR REPLACE TRIGGER pacientes_avanzar_id AFTER INSERT ON pacientes REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER pacientes_actualizado BEFORE UPDATE ON pacientes FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- Cada consentimiento es un hecho con su prueba (lo que marcó o escribió el paciente). El estado
-- vigente es el último registro de cada tipo.
CREATE TABLE IF NOT EXISTS consentimientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL,
  tipo TEXT NOT NULL,
  estado TEXT NOT NULL,
  fuente TEXT NOT NULL,
  prueba VARCHAR(500),
  registrado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  registrado_por VARCHAR(120),
  CONSTRAINT consentimientos_tipo_chk CHECK (tipo IN ('whatsapp_servicio','whatsapp_marketing','email_marketing','datos_salud','imagenes','resenas')),
  CONSTRAINT consentimientos_estado_chk CHECK (estado IN ('otorgado','revocado')),
  CONSTRAINT consentimientos_fuente_chk CHECK (fuente IN ('formulario','whatsapp','recepcion','web','importacion','otro')),
  CONSTRAINT cons_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS cons_vigente ON consentimientos (paciente_id, tipo, registrado_en);
CREATE OR REPLACE TRIGGER consentimientos_avanzar_id AFTER INSERT ON consentimientos REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS usuarios (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(160) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  rol TEXT NOT NULL,
  profesional_id SMALLINT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_rol_chk CHECK (rol IN ('direccion','recepcion','medico','estetica','marketing','admin')),
  CONSTRAINT usuario_prof FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE SET NULL
);
-- El email no distingue mayúsculas (en MariaDB, UNIQUE con utf8mb4_unicode_ci tampoco): único sobre lower().
CREATE UNIQUE INDEX IF NOT EXISTS usuario_email ON usuarios (lower(email));
CREATE INDEX IF NOT EXISTS usuario_prof_idx ON usuarios (profesional_id);
CREATE OR REPLACE TRIGGER usuarios_avanzar_id AFTER INSERT ON usuarios REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Registro de hechos (solo se añade). «Se guardan hechos, no resultados»: con esto se reconstruye
-- cualquier conversación, cita o decisión de la IA.
CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(60) NOT NULL,
  entidad VARCHAR(40),
  entidad_id VARCHAR(80),
  actor VARCHAR(80) NOT NULL DEFAULT 'sistema',
  datos TEXT,
  creado_en TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT eventos_datos_json CHECK (datos IS NULL OR datos::jsonb IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS eventos_entidad ON eventos (entidad, entidad_id, creado_en);
CREATE INDEX IF NOT EXISTS eventos_tipo ON eventos (tipo, creado_en);
CREATE OR REPLACE TRIGGER eventos_avanzar_id AFTER INSERT ON eventos REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Cola de trabajos: la procesa el cron cada minuto con SELECT … FOR UPDATE SKIP LOCKED.
CREATE TABLE IF NOT EXISTS cola (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(60) NOT NULL,
  carga TEXT,
  clave_unica VARCHAR(120),
  ejecutar_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  estado TEXT NOT NULL DEFAULT 'pendiente',
  intentos SMALLINT NOT NULL DEFAULT 0,
  max_intentos SMALLINT NOT NULL DEFAULT 5,
  bloqueado_hasta TIMESTAMPTZ,
  ultimo_error VARCHAR(1000),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  terminado_en TIMESTAMPTZ,
  CONSTRAINT cola_carga_json CHECK (carga IS NULL OR carga::jsonb IS NOT NULL),
  CONSTRAINT cola_estado_chk CHECK (estado IN ('pendiente','en_curso','hecho','fallido')),
  CONSTRAINT cola_intentos_pos CHECK (intentos >= 0),
  CONSTRAINT cola_max_intentos_pos CHECK (max_intentos >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS cola_clave ON cola (clave_unica);
CREATE INDEX IF NOT EXISTS cola_pendientes ON cola (estado, ejecutar_en);
CREATE OR REPLACE TRIGGER cola_avanzar_id AFTER INSERT ON cola REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS candados (
  nombre VARCHAR(80) PRIMARY KEY,
  dueno VARCHAR(120) NOT NULL,
  hasta TIMESTAMPTZ NOT NULL
);

-- Webhooks entrantes: se guardan tal cual, se responde 200 y se procesan (y si algo falla, el cron
-- los recoge).
CREATE TABLE IF NOT EXISTS webhooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor VARCHAR(30) NOT NULL,
  evento VARCHAR(60),
  id_externo VARCHAR(160),
  cuerpo TEXT NOT NULL,
  firma_ok BOOLEAN,
  recibido_en TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  procesado_en TIMESTAMPTZ,
  error VARCHAR(1000)
);
CREATE UNIQUE INDEX IF NOT EXISTS webhook_unico ON webhooks (proveedor, id_externo);
CREATE INDEX IF NOT EXISTS webhook_pendiente ON webhooks (procesado_en, recibido_en);
CREATE OR REPLACE TRIGGER webhooks_avanzar_id AFTER INSERT ON webhooks REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
