-- 002 · Agenda: citas con lo que ocupa cada una (sala con su limpieza, profesional y aparato), el
-- token de la página «Tu cita» y el número de versión para el .ics.

CREATE TABLE IF NOT EXISTS citas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL,
  tratamiento_id VARCHAR(80) NOT NULL,
  profesional_id SMALLINT,
  sala_id SMALLINT,
  equipo_id SMALLINT,
  inicio TIMESTAMPTZ NOT NULL,
  fin TIMESTAMPTZ NOT NULL,
  sala_desde TIMESTAMPTZ NOT NULL,
  sala_hasta TIMESTAMPTZ NOT NULL,
  prof_desde TIMESTAMPTZ NOT NULL,
  prof_hasta TIMESTAMPTZ NOT NULL,
  estado TEXT NOT NULL DEFAULT 'retenida',
  retenida_hasta TIMESTAMPTZ,
  origen TEXT NOT NULL DEFAULT 'recepcion',
  primera_visita BOOLEAN NOT NULL DEFAULT FALSE,
  token CHAR(43) NOT NULL,
  secuencia_ics INTEGER NOT NULL DEFAULT 0,
  reprograma_a_id INTEGER,
  notas VARCHAR(600),
  motivo_cancelacion VARCHAR(255),
  cancelada_por TEXT,
  cancelada_en TIMESTAMPTZ,
  confirmada_en TIMESTAMPTZ,
  creada_por VARCHAR(80) NOT NULL DEFAULT 'sistema',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT citas_estado_chk CHECK (estado IN ('retenida','confirmada','llegada','en_curso','completada','no_presentada','cancelada','reprogramada')),
  CONSTRAINT citas_origen_chk CHECK (origen IN ('ia_whatsapp','recepcion','telefono','web','treatwell','importacion','otro')),
  CONSTRAINT citas_secuencia_ics_pos CHECK (secuencia_ics >= 0),
  CONSTRAINT citas_cancelada_por_chk CHECK (cancelada_por IN ('paciente','clinica','sistema')),
  CONSTRAINT cita_orden CHECK (inicio < fin AND sala_desde < sala_hasta AND prof_desde <= prof_hasta),
  CONSTRAINT cita_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
  CONSTRAINT cita_trat_fk FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id),
  CONSTRAINT cita_prof_fk FOREIGN KEY (profesional_id) REFERENCES profesionales (id),
  CONSTRAINT cita_sala_fk FOREIGN KEY (sala_id) REFERENCES salas (id),
  CONSTRAINT cita_equipo_fk FOREIGN KEY (equipo_id) REFERENCES equipos (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS cita_token ON citas (token);
CREATE INDEX IF NOT EXISTS cita_inicio ON citas (inicio);
CREATE INDEX IF NOT EXISTS cita_paciente ON citas (paciente_id, inicio);
CREATE INDEX IF NOT EXISTS cita_sala ON citas (sala_id, sala_desde);
CREATE INDEX IF NOT EXISTS cita_prof ON citas (profesional_id, prof_desde);
CREATE INDEX IF NOT EXISTS cita_equipo ON citas (equipo_id, prof_desde);
CREATE INDEX IF NOT EXISTS cita_estado ON citas (estado, retenida_hasta);
CREATE INDEX IF NOT EXISTS cita_trat_fk_idx ON citas (tratamiento_id);
CREATE OR REPLACE TRIGGER citas_avanzar_id AFTER INSERT ON citas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER citas_actualizado BEFORE UPDATE ON citas FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- Lista de espera: quien quiere un hueco antes; cuando se libera uno que encaja, se le ofrece.
CREATE TABLE IF NOT EXISTS lista_espera (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL,
  tratamiento_id VARCHAR(80) NOT NULL,
  cita_actual_id INTEGER,
  desde_fecha DATE NOT NULL,
  hasta_fecha DATE,
  franjas VARCHAR(120),
  estado TEXT NOT NULL DEFAULT 'esperando',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lista_espera_estado_chk CHECK (estado IN ('esperando','ofrecido','aceptado','caducado','cancelado')),
  CONSTRAINT le_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE,
  CONSTRAINT le_trat FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id)
);
CREATE INDEX IF NOT EXISTS le_estado ON lista_espera (estado, tratamiento_id);
CREATE INDEX IF NOT EXISTS le_paciente_idx ON lista_espera (paciente_id);
CREATE INDEX IF NOT EXISTS le_trat_idx ON lista_espera (tratamiento_id);
CREATE OR REPLACE TRIGGER lista_espera_avanzar_id AFTER INSERT ON lista_espera REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
