-- 003 · Repesca: leads, presupuestos, conversaciones y mensajes (cifrados), secuencias,
-- seguimientos con fecha, catálogo de ofertas, plantillas de WhatsApp y tareas para personas.

ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS baja_comercial_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS es_cliente BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER,
  telefono VARCHAR(20),
  nombre VARCHAR(120),
  email VARCHAR(160),
  origen TEXT NOT NULL,
  campana VARCHAR(160),
  conjunto VARCHAR(160),
  anuncio VARCHAR(160),
  anuncio_id VARCHAR(60),
  ctwa_clid VARCHAR(120),
  codigo_web VARCHAR(40),
  utm TEXT,
  tratamiento_interes_id VARCHAR(80),
  texto_inicial VARCHAR(600),
  etapa TEXT NOT NULL DEFAULT 'nuevo',
  motivo_perdida VARCHAR(40),
  ghl_contact_id VARCHAR(60),
  ghl_opportunity_id VARCHAR(60),
  id_externo VARCHAR(120),
  cita_id INTEGER,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  primer_contacto_en TIMESTAMPTZ,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT leads_origen_chk CHECK (origen IN ('meta_formulario','meta_ctwa','web_whatsapp','ghl','treatwell','telefono','recepcion','google','referido','otro')),
  CONSTRAINT leads_utm_json CHECK (utm IS NULL OR utm::jsonb IS NOT NULL),
  CONSTRAINT leads_etapa_chk CHECK (etapa IN ('nuevo','contactado','conversando','cita','asistio','vendido','perdido')),
  CONSTRAINT lead_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE SET NULL,
  CONSTRAINT lead_trat_fk FOREIGN KEY (tratamiento_interes_id) REFERENCES tratamientos (id) ON DELETE SET NULL,
  CONSTRAINT lead_cita_fk FOREIGN KEY (cita_id) REFERENCES citas (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS lead_externo ON leads (origen, id_externo);
CREATE INDEX IF NOT EXISTS lead_etapa ON leads (etapa, creado_en);
CREATE INDEX IF NOT EXISTS lead_paciente ON leads (paciente_id);
CREATE INDEX IF NOT EXISTS lead_trat_fk_idx ON leads (tratamiento_interes_id);
CREATE INDEX IF NOT EXISTS lead_cita_fk_idx ON leads (cita_id);
CREATE OR REPLACE TRIGGER leads_avanzar_id AFTER INSERT ON leads REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER leads_actualizado BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TABLE IF NOT EXISTS presupuestos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL,
  codigo VARCHAR(30),
  titulo VARCHAR(160) NOT NULL,
  importe_eur NUMERIC(10,2) NOT NULL,
  estado TEXT NOT NULL DEFAULT 'entregado',
  entregado_en TIMESTAMPTZ,
  valido_hasta DATE,
  profesional_id SMALLINT,
  motivo_rechazo VARCHAR(40),
  aceptado_en TIMESTAMPTZ,
  notas VARCHAR(600),
  flowww_id VARCHAR(60),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT presupuestos_estado_chk CHECK (estado IN ('borrador','entregado','aceptado','rechazado','caducado')),
  CONSTRAINT pres_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE,
  CONSTRAINT pres_prof_fk FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS pres_estado ON presupuestos (estado, entregado_en);
CREATE INDEX IF NOT EXISTS pres_paciente_fk_idx ON presupuestos (paciente_id);
CREATE INDEX IF NOT EXISTS pres_prof_fk_idx ON presupuestos (profesional_id);
CREATE OR REPLACE TRIGGER presupuestos_avanzar_id AFTER INSERT ON presupuestos REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS presupuesto_lineas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  presupuesto_id INTEGER NOT NULL,
  tratamiento_id VARCHAR(80),
  concepto VARCHAR(160) NOT NULL,
  sesiones INTEGER NOT NULL DEFAULT 1,
  importe_eur NUMERIC(10,2) NOT NULL,
  CONSTRAINT presupuesto_lineas_sesiones_pos CHECK (sesiones >= 0),
  CONSTRAINT pl_pres_fk FOREIGN KEY (presupuesto_id) REFERENCES presupuestos (id) ON DELETE CASCADE,
  CONSTRAINT pl_trat_fk FOREIGN KEY (tratamiento_id) REFERENCES tratamientos (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS pl_pres_fk_idx ON presupuesto_lineas (presupuesto_id);
CREATE INDEX IF NOT EXISTS pl_trat_fk_idx ON presupuesto_lineas (tratamiento_id);
CREATE OR REPLACE TRIGGER presupuesto_lineas_avanzar_id AFTER INSERT ON presupuesto_lineas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS conversaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER,
  lead_id INTEGER,
  telefono VARCHAR(20) NOT NULL,
  estado TEXT NOT NULL DEFAULT 'ia_activa',
  agente VARCHAR(40) NOT NULL DEFAULT 'repesca',
  contexto TEXT NOT NULL DEFAULT 'general',
  contexto_id INTEGER,
  asignada_a SMALLINT,
  ventana_hasta TIMESTAMPTZ,
  ultimo_entrante_en TIMESTAMPTZ,
  ultimo_saliente_en TIMESTAMPTZ,
  proximo_paso TEXT NOT NULL DEFAULT 'ninguno',
  proximo_paso_en TIMESTAMPTZ,
  ya_pregunto_cuando BOOLEAN NOT NULL DEFAULT FALSE,
  motivo_cierre VARCHAR(40),
  urgente BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT conversaciones_estado_chk CHECK (estado IN ('ia_activa','espera_persona','persona','esperando_paciente','pausada','cerrada')),
  CONSTRAINT conversaciones_contexto_chk CHECK (contexto IN ('lead','cancelacion','presupuesto','toca_repetir','dormido','vale_regalo','cita','general')),
  CONSTRAINT conversaciones_proximo_paso_chk CHECK (proximo_paso IN ('cita','seguimiento','persona','cerrada','espera_respuesta','ninguno')),
  CONSTRAINT conv_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE SET NULL,
  CONSTRAINT conv_lead_fk FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL,
  CONSTRAINT conv_usuario_fk FOREIGN KEY (asignada_a) REFERENCES usuarios (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS conv_telefono ON conversaciones (telefono);
CREATE INDEX IF NOT EXISTS conv_estado ON conversaciones (estado, actualizado_en);
CREATE INDEX IF NOT EXISTS conv_proximo ON conversaciones (proximo_paso, proximo_paso_en);
CREATE INDEX IF NOT EXISTS conv_paciente_fk_idx ON conversaciones (paciente_id);
CREATE INDEX IF NOT EXISTS conv_lead_fk_idx ON conversaciones (lead_id);
CREATE INDEX IF NOT EXISTS conv_usuario_fk_idx ON conversaciones (asignada_a);
CREATE OR REPLACE TRIGGER conversaciones_avanzar_id AFTER INSERT ON conversaciones REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER conversaciones_actualizado BEFORE UPDATE ON conversaciones FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- El texto va cifrado (AES-256-GCM) con la clave del servidor; en la base solo hay bytes.
CREATE TABLE IF NOT EXISTS mensajes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id INTEGER NOT NULL,
  direccion TEXT NOT NULL,
  autor TEXT NOT NULL,
  usuario_id SMALLINT,
  tipo TEXT NOT NULL DEFAULT 'texto',
  cuerpo_cifrado BYTEA,
  iv BYTEA,
  tag BYTEA,
  plantilla_id INTEGER,
  wa_id VARCHAR(120),
  estado TEXT NOT NULL DEFAULT 'pendiente',
  error_codigo VARCHAR(20),
  error_texto VARCHAR(255),
  coste_eur NUMERIC(7,4),
  intencion VARCHAR(40),
  creado_en TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT mensajes_direccion_chk CHECK (direccion IN ('entrante','saliente')),
  CONSTRAINT mensajes_autor_chk CHECK (autor IN ('paciente','ia','persona','sistema')),
  CONSTRAINT mensajes_tipo_chk CHECK (tipo IN ('texto','plantilla','audio','imagen','documento','boton','interactivo','sistema')),
  CONSTRAINT mensajes_iv_len CHECK (octet_length(iv) <= 16),
  CONSTRAINT mensajes_tag_len CHECK (octet_length(tag) <= 16),
  CONSTRAINT mensajes_estado_chk CHECK (estado IN ('pendiente','enviado','entregado','leido','fallido','recibido')),
  CONSTRAINT msg_conv_fk FOREIGN KEY (conversacion_id) REFERENCES conversaciones (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS msg_wa ON mensajes (wa_id);
CREATE INDEX IF NOT EXISTS msg_conv ON mensajes (conversacion_id, creado_en);
CREATE OR REPLACE TRIGGER mensajes_avanzar_id AFTER INSERT ON mensajes REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS inscripciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  secuencia VARCHAR(40) NOT NULL,
  paciente_id INTEGER,
  lead_id INTEGER,
  cita_id INTEGER,
  presupuesto_id INTEGER,
  conversacion_id INTEGER,
  inicio TIMESTAMPTZ NOT NULL,
  paso_actual SMALLINT NOT NULL DEFAULT 0,
  siguiente_en TIMESTAMPTZ,
  estado TEXT NOT NULL DEFAULT 'activa',
  motivo_fin VARCHAR(120),
  grupo_control BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT inscripciones_paso_actual_pos CHECK (paso_actual >= 0),
  CONSTRAINT inscripciones_estado_chk CHECK (estado IN ('activa','pausada','terminada','cancelada')),
  CONSTRAINT ins_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE,
  CONSTRAINT ins_lead_fk FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
  CONSTRAINT ins_pres_fk FOREIGN KEY (presupuesto_id) REFERENCES presupuestos (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ins_pendientes ON inscripciones (estado, siguiente_en);
CREATE INDEX IF NOT EXISTS ins_paciente ON inscripciones (paciente_id, estado);
CREATE INDEX IF NOT EXISTS ins_lead_fk_idx ON inscripciones (lead_id);
CREATE INDEX IF NOT EXISTS ins_pres_fk_idx ON inscripciones (presupuesto_id);
CREATE OR REPLACE TRIGGER inscripciones_avanzar_id AFTER INSERT ON inscripciones REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Los seguimientos con fecha: la «memoria» de la repesca vive aquí, no en la IA.
CREATE TABLE IF NOT EXISTS seguimientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER,
  lead_id INTEGER,
  conversacion_id INTEGER,
  contexto TEXT NOT NULL DEFAULT 'general',
  contexto_id INTEGER,
  motivo VARCHAR(40) NOT NULL,
  plazo_tipo VARCHAR(30),
  frase_cifrada BYTEA,
  frase_iv BYTEA,
  frase_tag BYTEA,
  programado_para TIMESTAMPTZ NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  creado_por TEXT NOT NULL DEFAULT 'ia',
  usuario_id SMALLINT,
  intentos SMALLINT NOT NULL DEFAULT 0,
  plantilla_uso VARCHAR(40) NOT NULL DEFAULT 'como_quedamos',
  resultado VARCHAR(160),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT seguimientos_contexto_chk CHECK (contexto IN ('lead','cancelacion','presupuesto','toca_repetir','dormido','vale_regalo','cita','general')),
  CONSTRAINT seguimientos_frase_iv_len CHECK (octet_length(frase_iv) <= 16),
  CONSTRAINT seguimientos_frase_tag_len CHECK (octet_length(frase_tag) <= 16),
  CONSTRAINT seguimientos_estado_chk CHECK (estado IN ('pendiente','enviado','cancelado','cumplido','fallido')),
  CONSTRAINT seguimientos_creado_por_chk CHECK (creado_por IN ('ia','persona','sistema')),
  CONSTRAINT seguimientos_intentos_pos CHECK (intentos >= 0),
  CONSTRAINT seg_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE,
  CONSTRAINT seg_conv_fk FOREIGN KEY (conversacion_id) REFERENCES conversaciones (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS seg_pendientes ON seguimientos (estado, programado_para);
CREATE INDEX IF NOT EXISTS seg_paciente ON seguimientos (paciente_id, estado);
CREATE INDEX IF NOT EXISTS seg_conv_fk_idx ON seguimientos (conversacion_id);
CREATE OR REPLACE TRIGGER seguimientos_avanzar_id AFTER INSERT ON seguimientos REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER seguimientos_actualizado BEFORE UPDATE ON seguimientos FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TABLE IF NOT EXISTS ofertas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  tipo TEXT NOT NULL,
  texto_paciente VARCHAR(400) NOT NULL,
  familias TEXT,
  tratamientos TEXT,
  importe_min NUMERIC(10,2),
  importe_max NUMERIC(10,2),
  max_por_paciente SMALLINT,
  requiere_aprobacion BOOLEAN NOT NULL DEFAULT FALSE,
  permitida_producto_sanitario BOOLEAN NOT NULL DEFAULT FALSE,
  prioridad SMALLINT NOT NULL DEFAULT 0,
  vigente_desde DATE,
  vigente_hasta DATE,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  aprobada_por VARCHAR(120),
  CONSTRAINT ofertas_tipo_chk CHECK (tipo IN ('plazos','bono','alternativa','promocion','descuento','valoracion','regalo')),
  CONSTRAINT ofertas_familias_json CHECK (familias IS NULL OR familias::jsonb IS NOT NULL),
  CONSTRAINT ofertas_tratamientos_json CHECK (tratamientos IS NULL OR tratamientos::jsonb IS NOT NULL),
  CONSTRAINT ofertas_max_por_paciente_pos CHECK (max_por_paciente >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS ofertas_codigo ON ofertas (codigo);
CREATE OR REPLACE TRIGGER ofertas_avanzar_id AFTER INSERT ON ofertas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS ofertas_hechas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oferta_id INTEGER NOT NULL,
  paciente_id INTEGER,
  lead_id INTEGER,
  conversacion_id INTEGER,
  presupuesto_id INTEGER,
  estado TEXT NOT NULL DEFAULT 'propuesta',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ofertas_hechas_estado_chk CHECK (estado IN ('pendiente_aprobacion','propuesta','aceptada','rechazada','caducada','denegada')),
  CONSTRAINT oh_oferta_fk FOREIGN KEY (oferta_id) REFERENCES ofertas (id),
  CONSTRAINT oh_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS oh_paciente ON ofertas_hechas (paciente_id, creado_en);
CREATE INDEX IF NOT EXISTS oh_oferta_fk_idx ON ofertas_hechas (oferta_id);
CREATE OR REPLACE TRIGGER ofertas_hechas_avanzar_id AFTER INSERT ON ofertas_hechas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS plantillas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(512) NOT NULL,
  uso VARCHAR(40) NOT NULL,
  categoria TEXT NOT NULL,
  categoria_meta VARCHAR(20),
  idioma VARCHAR(10) NOT NULL DEFAULT 'es',
  cabecera TEXT,
  cuerpo TEXT NOT NULL,
  pie VARCHAR(60),
  botones TEXT,
  ejemplos TEXT,
  estado TEXT NOT NULL DEFAULT 'borrador',
  motivo_rechazo VARCHAR(255),
  calidad TEXT NOT NULL DEFAULT 'pendiente',
  meta_id VARCHAR(60),
  version INTEGER NOT NULL DEFAULT 1,
  reserva_de_id INTEGER,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT plantillas_categoria_chk CHECK (categoria IN ('utilidad','marketing','autenticacion')),
  CONSTRAINT plantillas_cabecera_json CHECK (cabecera IS NULL OR cabecera::jsonb IS NOT NULL),
  CONSTRAINT plantillas_botones_json CHECK (botones IS NULL OR botones::jsonb IS NOT NULL),
  CONSTRAINT plantillas_ejemplos_json CHECK (ejemplos IS NULL OR ejemplos::jsonb IS NOT NULL),
  CONSTRAINT plantillas_estado_chk CHECK (estado IN ('borrador','en_revision','aprobada','rechazada','pausada','desactivada')),
  CONSTRAINT plantillas_calidad_chk CHECK (calidad IN ('verde','amarilla','roja','pendiente')),
  CONSTRAINT plantillas_version_pos CHECK (version >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS plantilla_nombre ON plantillas (nombre, idioma);
CREATE INDEX IF NOT EXISTS plantilla_uso ON plantillas (uso, estado);
CREATE OR REPLACE TRIGGER plantillas_avanzar_id AFTER INSERT ON plantillas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER plantillas_actualizado BEFORE UPDATE ON plantillas FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TABLE IF NOT EXISTS tareas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  paciente_id INTEGER,
  conversacion_id INTEGER,
  responsable_id SMALLINT,
  urgente BOOLEAN NOT NULL DEFAULT FALSE,
  vence_en TIMESTAMPTZ NOT NULL,
  estado TEXT NOT NULL DEFAULT 'abierta',
  resultado VARCHAR(255),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  hecha_en TIMESTAMPTZ,
  CONSTRAINT tareas_tipo_chk CHECK (tipo IN ('llamar','atender_conversacion','aprobar_oferta','aprobar_respuesta','revisar_ia','otro')),
  CONSTRAINT tareas_estado_chk CHECK (estado IN ('abierta','hecha','cancelada')),
  CONSTRAINT tarea_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE,
  CONSTRAINT tarea_conv_fk FOREIGN KEY (conversacion_id) REFERENCES conversaciones (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS tarea_abierta ON tareas (estado, vence_en);
CREATE INDEX IF NOT EXISTS tarea_paciente_fk_idx ON tareas (paciente_id);
CREATE INDEX IF NOT EXISTS tarea_conv_fk_idx ON tareas (conversacion_id);
CREATE OR REPLACE TRIGGER tareas_avanzar_id AFTER INSERT ON tareas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
