-- 004 · Reseñas y Google Business Profile: reseñas con su análisis y respuesta (aprobada por una
-- persona), peticiones tras cada cita con su enlace corto, publicaciones de la ficha y métricas.

CREATE TABLE IF NOT EXISTS resenas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  google_id VARCHAR(160) NOT NULL,
  autor VARCHAR(160),
  nota SMALLINT NOT NULL,
  texto TEXT,
  publicada_en TIMESTAMPTZ NOT NULL,
  temas TEXT,
  sentimiento TEXT,
  prioridad TEXT NOT NULL DEFAULT 'normal',
  borrador_respuesta TEXT,
  respuesta TEXT,
  estado TEXT NOT NULL DEFAULT 'nueva',
  aprobada_por VARCHAR(120),
  respondida_en TIMESTAMPTZ,
  paciente_id INTEGER,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resenas_nota_pos CHECK (nota >= 0),
  CONSTRAINT resenas_temas_json CHECK (temas IS NULL OR temas::jsonb IS NOT NULL),
  CONSTRAINT resenas_sentimiento_chk CHECK (sentimiento IN ('positivo','mixto','negativo')),
  CONSTRAINT resenas_prioridad_chk CHECK (prioridad IN ('alta','media','normal')),
  CONSTRAINT resenas_estado_chk CHECK (estado IN ('nueva','borrador','aprobada','publicada','ignorada')),
  CONSTRAINT resena_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS resena_google ON resenas (google_id);
CREATE INDEX IF NOT EXISTS resena_estado ON resenas (estado, publicada_en);
CREATE INDEX IF NOT EXISTS resena_paciente_fk_idx ON resenas (paciente_id);
CREATE OR REPLACE TRIGGER resenas_avanzar_id AFTER INSERT ON resenas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS peticiones_resena (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cita_id INTEGER NOT NULL,
  paciente_id INTEGER NOT NULL,
  token CHAR(22) NOT NULL,
  programada_para TIMESTAMPTZ NOT NULL,
  enviada_en TIMESTAMPTZ,
  pulsada_en TIMESTAMPTZ,
  resena_id INTEGER,
  estado TEXT NOT NULL DEFAULT 'programada',
  motivo VARCHAR(160),
  CONSTRAINT peticiones_resena_estado_chk CHECK (estado IN ('programada','enviada','omitida','fallida')),
  CONSTRAINT peticion_cita_fk FOREIGN KEY (cita_id) REFERENCES citas (id) ON DELETE CASCADE,
  CONSTRAINT peticion_paciente_fk FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS peticion_cita ON peticiones_resena (cita_id);
CREATE UNIQUE INDEX IF NOT EXISTS peticion_token ON peticiones_resena (token);
CREATE INDEX IF NOT EXISTS peticion_pendiente ON peticiones_resena (estado, programada_para);
CREATE INDEX IF NOT EXISTS peticion_paciente_fk_idx ON peticiones_resena (paciente_id);
CREATE OR REPLACE TRIGGER peticiones_resena_avanzar_id AFTER INSERT ON peticiones_resena REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

CREATE TABLE IF NOT EXISTS publicaciones_gbp (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'novedad',
  titulo VARCHAR(160) NOT NULL,
  texto VARCHAR(1500) NOT NULL,
  boton_url VARCHAR(600),
  estado TEXT NOT NULL DEFAULT 'idea',
  programada_para DATE,
  google_id VARCHAR(160),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT publicaciones_gbp_tipo_chk CHECK (tipo IN ('novedad','oferta','evento')),
  CONSTRAINT publicaciones_gbp_estado_chk CHECK (estado IN ('idea','borrador','aprobada','publicada','descartada'))
);
CREATE UNIQUE INDEX IF NOT EXISTS publicaciones_gbp_codigo ON publicaciones_gbp (codigo);
CREATE OR REPLACE TRIGGER publicaciones_gbp_avanzar_id AFTER INSERT ON publicaciones_gbp REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Métricas diarias de la ficha (Performance API) y búsquedas del mes (palabras con impresiones).
CREATE TABLE IF NOT EXISTS metricas_gbp (
  fecha DATE NOT NULL,
  metrica VARCHAR(60) NOT NULL,
  valor INTEGER NOT NULL,
  CONSTRAINT metricas_gbp_valor_pos CHECK (valor >= 0),
  PRIMARY KEY (fecha, metrica)
);

CREATE TABLE IF NOT EXISTS busquedas_gbp (
  mes CHAR(7) NOT NULL,
  palabra VARCHAR(160) NOT NULL,
  impresiones INTEGER,
  umbral VARCHAR(20),
  CONSTRAINT busquedas_gbp_impresiones_pos CHECK (impresiones >= 0),
  PRIMARY KEY (mes, palabra)
);
