-- 009 · Huecos que no se pierden: cambiar la cita por WhatsApp (la antigua queda «reprogramada»
-- y apunta a la nueva), cancelarla con confirmación, y lista de espera: cuando se libera un hueco,
-- se le guarda 30 minutos al primero que encaja y se le ofrece; si no lo quiere, pasa al siguiente.

-- La cita que se está cambiando mientras se le proponen huecos, y la pregunta que se le ha hecho
-- («¿La cancelo?», «¿Te busco otro momento?», «¿Te aviso si se libera un hueco?») para entender
-- su «sí» o su «no». La pregunta solo vale mientras sea lo último que le hemos escrito.
ALTER TABLE conversaciones
  ADD COLUMN IF NOT EXISTS reprograma_cita_id INTEGER,
  ADD COLUMN IF NOT EXISTS pregunta_pendiente TEXT CONSTRAINT conversaciones_pregunta_pendiente_json CHECK (pregunta_pendiente IS NULL OR pregunta_pendiente::jsonb IS NOT NULL);

-- Para encontrar deprisa los huecos que se acaban de liberar (canceladas y cambiadas).
CREATE INDEX IF NOT EXISTS cita_liberada ON citas (estado, cancelada_en);

-- cita_actual_id (de la 002) es la cita que quiere adelantar: solo si se enlaza al apuntarle. El
-- índice de la clave foránea de paciente_id (le_paciente_idx, de la 002) queda cubierto por el
-- compuesto, que va con otro nombre: se quita el viejo, como hacía MariaDB por su cuenta.
ALTER TABLE lista_espera
  ADD COLUMN IF NOT EXISTS origen TEXT NOT NULL DEFAULT 'panel' CONSTRAINT lista_espera_origen_chk CHECK (origen IN ('panel','whatsapp')),
  ADD COLUMN IF NOT EXISTS creado_por VARCHAR(120),
  ADD COLUMN IF NOT EXISTS notas VARCHAR(255),
  ADD COLUMN IF NOT EXISTS conversacion_id INTEGER,
  ADD COLUMN IF NOT EXISTS cerrado_en TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS le_paciente_estado ON lista_espera (paciente_id, estado);
DROP INDEX IF EXISTS le_paciente_idx;

-- Cada hueco ofrecido a alguien de la lista. La cita retenida es la que le guarda el hueco mientras
-- contesta: la agenda ya no lo da por libre, así que nunca se ofrece a dos a la vez. La clave única
-- impide ofrecerle dos veces el mismo hueco a la misma persona (si dijo que no, pasa al siguiente;
-- si el aviso no salió, la oferta se borra y conserva su turno).
--   cambia_cita_id  la cita que se le adelanta si lo acepta (la que enlazó al apuntarse)
--   aviso           cómo se le avisó: el texto nombra la cita que se le cambia; la plantilla, no (y
--                   antes de cambiársela se le pregunta)
--   mensaje_id      el mensaje del aviso (si Meta dice que no le llegó, el hueco pasa al siguiente)
--   tarea_id        la tarea de recepción si su conversación pasó a una persona con la oferta en curso
CREATE TABLE IF NOT EXISTS lista_espera_ofertas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lista_espera_id INTEGER NOT NULL,
  cita_id INTEGER,
  liberada_por_cita_id INTEGER,
  cambia_cita_id INTEGER,
  tratamiento_id VARCHAR(80) NOT NULL,
  inicio TIMESTAMPTZ NOT NULL,
  estado TEXT NOT NULL DEFAULT 'ofrecida',
  conversacion_id INTEGER,
  aviso TEXT,
  mensaje_id BIGINT,
  tarea_id INTEGER,
  ofrecida_en TIMESTAMPTZ NOT NULL,
  caduca_en TIMESTAMPTZ NOT NULL,
  respondida_en TIMESTAMPTZ,
  CONSTRAINT lista_espera_ofertas_estado_chk CHECK (estado IN ('ofrecida','aceptada','rechazada','caducada','anulada')),
  CONSTRAINT lista_espera_ofertas_aviso_chk CHECK (aviso IN ('texto','plantilla')),
  CONSTRAINT leo_lista FOREIGN KEY (lista_espera_id) REFERENCES lista_espera (id) ON DELETE CASCADE,
  CONSTRAINT leo_cita FOREIGN KEY (cita_id) REFERENCES citas (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS leo_una_vez ON lista_espera_ofertas (lista_espera_id, tratamiento_id, inicio);
CREATE INDEX IF NOT EXISTS leo_estado ON lista_espera_ofertas (estado, caduca_en);
CREATE INDEX IF NOT EXISTS leo_hueco ON lista_espera_ofertas (tratamiento_id, inicio, estado);
CREATE INDEX IF NOT EXISTS leo_mensaje ON lista_espera_ofertas (mensaje_id);
CREATE INDEX IF NOT EXISTS leo_cita_idx ON lista_espera_ofertas (cita_id);
CREATE OR REPLACE TRIGGER lista_espera_ofertas_avanzar_id AFTER INSERT ON lista_espera_ofertas REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
