-- 010 · Privacidad de la cita y «Añadir al calendario» con un toque.
--
-- El token de «Tu cita» deja de guardarse en claro. En la base quedan su huella (SHA-256), para
-- encontrar la cita, y el token cifrado con CLAVE_CIFRADO (AES-256-GCM), para volver a mandar el
-- enlace. El enlace caduca 30 días después de la cita (token_caduca_en). Los tokens de antes pasan a
-- token_antiguo con su huella ya calculada (sus enlaces siguen valiendo): los cifra migrar() nada más
-- aplicar esta migración (en SQL no se puede: la clave solo la tiene la app) y deja token_antiguo
-- vacío; si migrar se lanza sin CLAVE_CIFRADO, lo avisa y los cifra la app al usarlos. Una migración
-- posterior podrá quitar la columna (y su uso en servidor/agenda.js).
--
-- El .ics lleva un UID aleatorio guardado en la cita (uid_ics, RFC 7986: sin datos del servidor ni
-- del número de cita). Las citas de antes conservan el que ya tenían los calendarios
-- (cita-<id>@iemec-clinic.com): así su anulación sigue casando con el evento que importaron.
--
-- Sedes: dónde está cada sala. LOCATION, GEO y el mapa de WhatsApp salen de la sede de la sala de la
-- cita; una sala sin sede (sede_id NULL) está en la principal. Se da de alta la de IEMEC con los datos
-- públicos de su web (dirección y coordenadas de sus datos estructurados).

CREATE TABLE IF NOT EXISTS sedes (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  cp VARCHAR(10),
  municipio VARCHAR(80),
  provincia VARCHAR(80),
  lat NUMERIC(10,7),
  lng NUMERIC(10,7),
  indicaciones VARCHAR(400),
  principal BOOLEAN NOT NULL DEFAULT FALSE,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS sedes_codigo ON sedes (codigo);
CREATE OR REPLACE TRIGGER sedes_avanzar_id AFTER INSERT ON sedes REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
CREATE OR REPLACE TRIGGER sedes_actualizado BEFORE UPDATE ON sedes FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

INSERT INTO sedes (codigo, nombre, direccion, cp, municipio, provincia, lat, lng, principal)
VALUES ('iemec', 'IEMEC', 'Av. Siglo XXI, 13, local 35', '28660', 'Boadilla del Monte', 'Madrid', 40.4066059, -3.9001441, TRUE)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE salas
  ADD COLUMN IF NOT EXISTS sede_id SMALLINT,
  ADD CONSTRAINT sala_sede_fk FOREIGN KEY (sede_id) REFERENCES sedes (id);
CREATE INDEX IF NOT EXISTS sala_sede_fk_idx ON salas (sede_id);

-- El token en claro, fuera de su sitio (y sin su índice): nada vuelve a escribirlo.
ALTER TABLE citas RENAME COLUMN token TO token_antiguo;
ALTER TABLE citas ALTER COLUMN token_antiguo DROP NOT NULL;
DROP INDEX IF EXISTS cita_token;

ALTER TABLE citas
  ADD COLUMN IF NOT EXISTS token_hash BYTEA CONSTRAINT citas_token_hash_len CHECK (octet_length(token_hash) = 32),
  ADD COLUMN IF NOT EXISTS token_cifrado BYTEA CONSTRAINT citas_token_cifrado_len CHECK (octet_length(token_cifrado) <= 64),
  ADD COLUMN IF NOT EXISTS token_iv BYTEA CONSTRAINT citas_token_iv_len CHECK (octet_length(token_iv) <= 16),
  ADD COLUMN IF NOT EXISTS token_tag BYTEA CONSTRAINT citas_token_tag_len CHECK (octet_length(token_tag) <= 16),
  ADD COLUMN IF NOT EXISTS token_caduca_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS uid_ics VARCHAR(80);

-- sha256() de PostgreSQL (sin extensiones) da lo mismo que UNHEX(SHA2(…, 256)) de MariaDB y que el
-- createHash('sha256') de la app. 30 días son 720 horas: una duración, no «30 días de calendario»,
-- que cambiaría con la zona de la sesión al cruzar un cambio de hora.
UPDATE citas SET token_hash = sha256(convert_to(token_antiguo, 'UTF8')) WHERE token_hash IS NULL AND token_antiguo IS NOT NULL;
UPDATE citas SET token_caduca_en = fin + INTERVAL '720 hours' WHERE token_caduca_en IS NULL;
UPDATE citas SET uid_ics = 'cita-' || id || '@iemec-clinic.com' WHERE uid_ics IS NULL;

ALTER TABLE citas ALTER COLUMN token_hash SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cita_token_hash ON citas (token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS cita_uid_ics ON citas (uid_ics);
