-- 013 · Acceso del personal con passkeys (WebAuthn), en lugar de la clave compartida PANEL_CLAVE.
-- Cada persona del equipo es un usuario con su rol y entra con una o varias passkeys (su móvil, el
-- ordenador de recepción…). Se da de alta con un enlace de un solo uso que caduca a las 24 horas: en
-- la base solo está la huella SHA-256 del token. Los retos de WebAuthn se guardan aquí, caducan a los
-- pocos minutos y se gastan al usarlos. Los intentos de entrar se cuentan por la huella de la IP (la IP
-- no se guarda). Una sesión deja de valer al momento si el usuario se desactiva, si se cierran sus
-- sesiones (sesion_version) o si se borra la passkey con la que entró.
-- Los identificadores de WebAuthn van en base64url, que distingue mayúsculas: en MariaDB por eso eran
-- ascii_bin. PostgreSQL compara el texto siempre tal cual, así que aquí basta con VARCHAR.

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS id_webauthn VARCHAR(64),
  ADD COLUMN IF NOT EXISTS sesion_version INTEGER NOT NULL DEFAULT 0 CONSTRAINT usuarios_sesion_version_pos CHECK (sesion_version >= 0),
  ADD COLUMN IF NOT EXISTS desactivado_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ultimo_acceso_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS creado_por VARCHAR(160);
CREATE UNIQUE INDEX IF NOT EXISTS usuario_webauthn ON usuarios (id_webauthn);

-- Las sesiones abiertas antes de las passkeys (con la clave compartida, fuera cual fuera el rol) dejan
-- de valer: cada persona vuelve a entrar con su passkey o, dirección, con la clave de emergencia.
UPDATE usuarios SET sesion_version = sesion_version + 1;

-- Las passkeys de cada persona. La clave privada nunca sale de su dispositivo: aquí solo está la
-- pública (COSE) y el contador de firmas, que tiene que avanzar (si no, puede ser una copia). El
-- contador es de 32 bits sin signo (hasta 4.294.967.295): BIGINT, porque un INTEGER no llega.
CREATE TABLE IF NOT EXISTS passkeys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id SMALLINT NOT NULL,
  credencial_id VARCHAR(1400) NOT NULL,
  clave_publica BYTEA NOT NULL,
  contador BIGINT NOT NULL DEFAULT 0,
  transportes TEXT,
  dispositivo VARCHAR(80) NOT NULL,
  sincronizada BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultimo_uso_en TIMESTAMPTZ,
  CONSTRAINT passkeys_contador_pos CHECK (contador >= 0),
  CONSTRAINT passkeys_transportes_json CHECK (transportes IS NULL OR transportes::jsonb IS NOT NULL),
  CONSTRAINT passkey_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS passkey_credencial ON passkeys (credencial_id);
CREATE INDEX IF NOT EXISTS passkey_usuario ON passkeys (usuario_id);
CREATE OR REPLACE TRIGGER passkeys_avanzar_id AFTER INSERT ON passkeys REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Enlaces de alta (y de passkey nueva, si alguien pierde las suyas). Un enlace nuevo anula el anterior.
-- creada_por_rol: el rol de quien lo dio (NULL, la consola del servidor). Una cuenta de dirección solo se
-- estrena con un enlace de dirección: al pasar a dirección, los que dio otro rol se anulan.
CREATE TABLE IF NOT EXISTS invitaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id SMALLINT NOT NULL,
  token_huella CHAR(64) NOT NULL,
  caduca_en TIMESTAMPTZ NOT NULL,
  usada_en TIMESTAMPTZ,
  anulada_en TIMESTAMPTZ,
  creada_por VARCHAR(160) NOT NULL,
  creada_por_rol TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT invitaciones_creada_por_rol_chk CHECK (creada_por_rol IN ('direccion','recepcion','medico','estetica','marketing','admin')),
  CONSTRAINT invitacion_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS invitacion_token ON invitaciones (token_huella);
CREATE INDEX IF NOT EXISTS invitacion_usuario ON invitaciones (usuario_id, caduca_en);
CREATE OR REPLACE TRIGGER invitaciones_avanzar_id AFTER INSERT ON invitaciones REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();

-- Retos de un solo uso: «alta» (con su enlace), «entrar» y «nueva_passkey» (con sesión).
CREATE TABLE IF NOT EXISTS retos_webauthn (
  reto VARCHAR(128) PRIMARY KEY,
  proposito TEXT NOT NULL,
  usuario_id SMALLINT,
  invitacion_id INTEGER,
  caduca_en TIMESTAMPTZ NOT NULL,
  CONSTRAINT retos_webauthn_proposito_chk CHECK (proposito IN ('alta','entrar','nueva_passkey')),
  CONSTRAINT reto_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
  CONSTRAINT reto_invitacion_fk FOREIGN KEY (invitacion_id) REFERENCES invitaciones (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS reto_caducidad ON retos_webauthn (caduca_en);
CREATE INDEX IF NOT EXISTS reto_usuario_fk_idx ON retos_webauthn (usuario_id);
CREATE INDEX IF NOT EXISTS reto_invitacion_fk_idx ON retos_webauthn (invitacion_id);

-- Límite de intentos por ventana (p. ej. «fallos:» + huella de la IP). El cron borra las ventanas
-- pasadas.
CREATE TABLE IF NOT EXISTS limites_acceso (
  clave VARCHAR(80) PRIMARY KEY,
  intentos INTEGER NOT NULL DEFAULT 0,
  hasta TIMESTAMPTZ NOT NULL,
  CONSTRAINT limites_acceso_intentos_pos CHECK (intentos >= 0)
);
CREATE INDEX IF NOT EXISTS limite_hasta ON limites_acceso (hasta);
