-- 015 · El formulario «Te llamamos» de la web pública (POST /web/contacto): la prueba de cada
-- envío con sus consentimientos (RGPD, art. 7.1: hay que poder demostrarlos), por separado el de los
-- datos (obligatorio para contestar) y el comercial (opcional), con la fecha, la versión de los
-- textos que se aceptaron, la página y cómo prefiere que le contesten.
-- Sin clave ajena a leads: la prueba se conserva, bloqueada, aunque se borre el lead (LSSI, art. 45;
-- LOPDGDD, art. 32). La huella del envío evita duplicados si la web reintenta el mismo envío.
CREATE TABLE IF NOT EXISTS solicitudes_web (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER,
  telefono VARCHAR(20),
  pagina VARCHAR(200) NOT NULL,
  ref VARCHAR(40),
  tratamiento_id VARCHAR(80),
  interes VARCHAR(80),
  preferencia TEXT NOT NULL,
  consentimiento_datos BOOLEAN NOT NULL,
  consentimiento_comercial BOOLEAN NOT NULL,
  version_textos VARCHAR(20) NOT NULL,
  huella_envio CHAR(64) NOT NULL,
  enviado_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT solicitudes_web_preferencia_chk CHECK (preferencia IN ('whatsapp','llamada','correo'))
);
CREATE UNIQUE INDEX IF NOT EXISTS solicitud_envio ON solicitudes_web (huella_envio);
CREATE INDEX IF NOT EXISTS solicitud_lead ON solicitudes_web (lead_id);
CREATE INDEX IF NOT EXISTS solicitud_telefono ON solicitudes_web (telefono, enviado_en);
CREATE OR REPLACE TRIGGER solicitudes_web_avanzar_id AFTER INSERT ON solicitudes_web REFERENCING NEW TABLE AS nuevas FOR EACH STATEMENT EXECUTE FUNCTION avanzar_identidad();
